// Generated by moon-bindgen. Do not edit.
#include <moonbit.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

typedef struct moon_bindgen_c_LZ4_streamDecode_t_internal moon_bindgen_c_LZ4_streamDecode_t_internal;
typedef union moon_bindgen_c_LZ4_streamDecode_u moon_bindgen_c_LZ4_streamDecode_u;
typedef struct moon_bindgen_c_LZ4_stream_t_internal moon_bindgen_c_LZ4_stream_t_internal;
typedef union moon_bindgen_c_LZ4_stream_u moon_bindgen_c_LZ4_stream_u;
typedef struct moon_bindgen_c___darwin_pthread_handler_rec moon_bindgen_c___darwin_pthread_handler_rec;
typedef union moon_bindgen_c___mbstate_t moon_bindgen_c___mbstate_t;
typedef struct moon_bindgen_c__opaque_pthread_attr_t moon_bindgen_c__opaque_pthread_attr_t;
typedef struct moon_bindgen_c__opaque_pthread_cond_t moon_bindgen_c__opaque_pthread_cond_t;
typedef struct moon_bindgen_c__opaque_pthread_condattr_t moon_bindgen_c__opaque_pthread_condattr_t;
typedef struct moon_bindgen_c__opaque_pthread_mutex_t moon_bindgen_c__opaque_pthread_mutex_t;
typedef struct moon_bindgen_c__opaque_pthread_mutexattr_t moon_bindgen_c__opaque_pthread_mutexattr_t;
typedef struct moon_bindgen_c__opaque_pthread_once_t moon_bindgen_c__opaque_pthread_once_t;
typedef struct moon_bindgen_c__opaque_pthread_rwlock_t moon_bindgen_c__opaque_pthread_rwlock_t;
typedef struct moon_bindgen_c__opaque_pthread_rwlockattr_t moon_bindgen_c__opaque_pthread_rwlockattr_t;
typedef struct moon_bindgen_c__opaque_pthread_t moon_bindgen_c__opaque_pthread_t;

struct moon_bindgen_c_LZ4_streamDecode_t_internal {
  const unsigned char * externalDict;
  const unsigned char * prefixEnd;
  size_t extDictSize;
  size_t prefixSize;
};

struct moon_bindgen_c_LZ4_stream_t_internal {
  uint32_t hashTable[4096];
  const unsigned char * dictionary;
  const moon_bindgen_c_LZ4_stream_t_internal * dictCtx;
  uint32_t currentOffset;
  uint32_t tableType;
  uint32_t dictSize;
};

MOONBIT_FFI_EXPORT
void *moon_bindgen_lz4_stream_decode_t_internal_new(const unsigned char * external_dict, const unsigned char * prefix_end, size_t ext_dict_size, size_t prefix_size) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_c_LZ4_streamDecode_t_internal));
  value->externalDict = external_dict;
  value->prefixEnd = prefix_end;
  value->extDictSize = ext_dict_size;
  value->prefixSize = prefix_size;
  return value;
}

MOONBIT_FFI_EXPORT
const unsigned char * moon_bindgen_lz4_stream_decode_t_internal_external_dict_get(void *self) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  return (const unsigned char *)value->externalDict;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_decode_t_internal_external_dict_set(void *self, const unsigned char * field) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  value->externalDict = field;
}

MOONBIT_FFI_EXPORT
const unsigned char * moon_bindgen_lz4_stream_decode_t_internal_prefix_end_get(void *self) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  return (const unsigned char *)value->prefixEnd;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_decode_t_internal_prefix_end_set(void *self, const unsigned char * field) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  value->prefixEnd = field;
}

MOONBIT_FFI_EXPORT
size_t moon_bindgen_lz4_stream_decode_t_internal_ext_dict_size_get(void *self) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  return value->extDictSize;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_decode_t_internal_ext_dict_size_set(void *self, size_t field) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  value->extDictSize = field;
}

MOONBIT_FFI_EXPORT
size_t moon_bindgen_lz4_stream_decode_t_internal_prefix_size_get(void *self) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  return value->prefixSize;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_decode_t_internal_prefix_size_set(void *self, size_t field) {
  moon_bindgen_c_LZ4_streamDecode_t_internal *value = (moon_bindgen_c_LZ4_streamDecode_t_internal *)self;
  value->prefixSize = field;
}

MOONBIT_FFI_EXPORT
void *moon_bindgen_lz4_stream_t_internal_new(uint32_t * hash_table, const unsigned char * dictionary, void * dict_ctx, uint32_t current_offset, uint32_t table_type, uint32_t dict_size) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_c_LZ4_stream_t_internal));
  memcpy(value->hashTable, hash_table, sizeof(value->hashTable));
  value->dictionary = dictionary;
  value->dictCtx = dict_ctx;
  value->currentOffset = current_offset;
  value->tableType = table_type;
  value->dictSize = dict_size;
  return value;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_hash_table_get(void *self, void *out) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  memcpy(out, value->hashTable, sizeof(value->hashTable));
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_hash_table_set(void *self, void *field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  memcpy(value->hashTable, field, sizeof(value->hashTable));
}

MOONBIT_FFI_EXPORT
const unsigned char * moon_bindgen_lz4_stream_t_internal_dictionary_get(void *self) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  return (const unsigned char *)value->dictionary;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_dictionary_set(void *self, const unsigned char * field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  value->dictionary = field;
}

MOONBIT_FFI_EXPORT
void * moon_bindgen_lz4_stream_t_internal_dict_ctx_get(void *self) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  return (void *)value->dictCtx;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_dict_ctx_set(void *self, void * field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  value->dictCtx = field;
}

MOONBIT_FFI_EXPORT
uint32_t moon_bindgen_lz4_stream_t_internal_current_offset_get(void *self) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  return value->currentOffset;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_current_offset_set(void *self, uint32_t field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  value->currentOffset = field;
}

MOONBIT_FFI_EXPORT
uint32_t moon_bindgen_lz4_stream_t_internal_table_type_get(void *self) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  return value->tableType;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_table_type_set(void *self, uint32_t field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  value->tableType = field;
}

MOONBIT_FFI_EXPORT
uint32_t moon_bindgen_lz4_stream_t_internal_dict_size_get(void *self) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  return value->dictSize;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_lz4_stream_t_internal_dict_size_set(void *self, uint32_t field) {
  moon_bindgen_c_LZ4_stream_t_internal *value = (moon_bindgen_c_LZ4_stream_t_internal *)self;
  value->dictSize = field;
}

