#include <stddef.h>
// Generated by moon-bindgen. Do not edit.
#include <moonbit.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

typedef struct moon_bindgen_c_TestContext moon_bindgen_c_TestContext;
typedef struct moon_bindgen_c_TestLine moon_bindgen_c_TestLine;
typedef struct moon_bindgen_c_TestPoint moon_bindgen_c_TestPoint;
typedef struct moon_bindgen_c_TestSlice moon_bindgen_c_TestSlice;

struct moon_bindgen_c_TestPoint {
  int32_t x;
  int32_t y;
  uint8_t rgba[4];
};

struct moon_bindgen_c_TestLine {
  moon_bindgen_c_TestPoint start;
  moon_bindgen_c_TestPoint end;
};

struct moon_bindgen_c_TestSlice {
  const uint8_t * data;
  uint64_t len;
};

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_line_start_x(moonbit_bytes_t value) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  return typed->start.x;
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_line_start_y(moonbit_bytes_t value) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  return typed->start.y;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_get_test_line_start_rgba(moonbit_bytes_t value, void *out) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  memcpy(out, typed->start.rgba, sizeof(typed->start.rgba));
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_line_end_x(moonbit_bytes_t value) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  return typed->end.x;
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_line_end_y(moonbit_bytes_t value) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  return typed->end.y;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_get_test_line_end_rgba(moonbit_bytes_t value, void *out) {
  moon_bindgen_c_TestLine *typed = (moon_bindgen_c_TestLine *)value;
  memcpy(out, typed->end.rgba, sizeof(typed->end.rgba));
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_point_x(moonbit_bytes_t value) {
  moon_bindgen_c_TestPoint *typed = (moon_bindgen_c_TestPoint *)value;
  return typed->x;
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_get_test_point_y(moonbit_bytes_t value) {
  moon_bindgen_c_TestPoint *typed = (moon_bindgen_c_TestPoint *)value;
  return typed->y;
}

MOONBIT_FFI_EXPORT
void moon_bindgen_get_test_point_rgba(moonbit_bytes_t value, void *out) {
  moon_bindgen_c_TestPoint *typed = (moon_bindgen_c_TestPoint *)value;
  memcpy(out, typed->rgba, sizeof(typed->rgba));
}

extern moon_bindgen_c_TestLine test_line_translate(moon_bindgen_c_TestLine line, int32_t dx, int32_t dy);
MOONBIT_FFI_EXPORT
moonbit_bytes_t moon_bindgen_test_line_translate(int32_t line_start_x, int32_t line_start_y, uint8_t * line_start_rgba, int32_t line_end_x, int32_t line_end_y, uint8_t * line_end_rgba, int32_t dx, int32_t dy) {
  moon_bindgen_c_TestLine moon_bindgen_arg_line;
  moon_bindgen_arg_line.start.x = line_start_x;
  moon_bindgen_arg_line.start.y = line_start_y;
  memcpy(moon_bindgen_arg_line.start.rgba, line_start_rgba, sizeof(moon_bindgen_arg_line.start.rgba));
  moon_bindgen_arg_line.end.x = line_end_x;
  moon_bindgen_arg_line.end.y = line_end_y;
  memcpy(moon_bindgen_arg_line.end.rgba, line_end_rgba, sizeof(moon_bindgen_arg_line.end.rgba));
  moon_bindgen_c_TestLine result = test_line_translate(moon_bindgen_arg_line, dx, dy);
  moonbit_bytes_t bytes = moonbit_make_bytes((int32_t)sizeof(result), 0);
  memcpy(bytes, &result, sizeof(result));
  return bytes;
}

extern int32_t test_point_score(moon_bindgen_c_TestPoint point);
MOONBIT_FFI_EXPORT
int32_t moon_bindgen_test_point_score(int32_t point_x, int32_t point_y, uint8_t * point_rgba) {
  moon_bindgen_c_TestPoint moon_bindgen_arg_point;
  moon_bindgen_arg_point.x = point_x;
  moon_bindgen_arg_point.y = point_y;
  memcpy(moon_bindgen_arg_point.rgba, point_rgba, sizeof(moon_bindgen_arg_point.rgba));
  return test_point_score(moon_bindgen_arg_point);
}

extern moon_bindgen_c_TestPoint test_point_translate(moon_bindgen_c_TestPoint point, int32_t dx, int32_t dy);
MOONBIT_FFI_EXPORT
moonbit_bytes_t moon_bindgen_test_point_translate(int32_t point_x, int32_t point_y, uint8_t * point_rgba, int32_t dx, int32_t dy) {
  moon_bindgen_c_TestPoint moon_bindgen_arg_point;
  moon_bindgen_arg_point.x = point_x;
  moon_bindgen_arg_point.y = point_y;
  memcpy(moon_bindgen_arg_point.rgba, point_rgba, sizeof(moon_bindgen_arg_point.rgba));
  moon_bindgen_c_TestPoint result = test_point_translate(moon_bindgen_arg_point, dx, dy);
  moonbit_bytes_t bytes = moonbit_make_bytes((int32_t)sizeof(result), 0);
  memcpy(bytes, &result, sizeof(result));
  return bytes;
}

extern uint32_t test_slice_sum(moon_bindgen_c_TestSlice slice);
MOONBIT_FFI_EXPORT
uint32_t moon_bindgen_test_slice_sum(moonbit_bytes_t slice_data, uint64_t slice_len) {
  moon_bindgen_c_TestSlice moon_bindgen_arg_slice;
  moon_bindgen_arg_slice.data = slice_data;
  moon_bindgen_arg_slice.len = slice_len;
  return test_slice_sum(moon_bindgen_arg_slice);
}

MOONBIT_FFI_EXPORT
void *moon_bindgen_constptr_byte_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_constptr_byte_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
moonbit_bytes_t moon_bindgen_constptr_byte_copy_bytes(const uint8_t *pointer, uint64_t length) {
  moonbit_bytes_t bytes = moonbit_make_bytes((int32_t)length, 0);
  if (length != 0) memcpy(bytes, pointer, (size_t)length);
  return bytes;
}

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_constptr_byte_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_constptr_byte_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_constptr_byte_deref(void *pointer) { return *(void **)pointer; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_int_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_int_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_int_read(const int32_t *pointer) { return *pointer; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_int_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_ptr_int_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_int_deref(void *pointer) { return *(void **)pointer; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_ptr_testcontext_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_ptr_ptr_testcontext_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_ptr_testcontext_deref(void *pointer) { return *(void **)pointer; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_testcontext_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_ptr_testcontext_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_testcontext_deref(void *pointer) { return *(void **)pointer; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_testcontext_null(void) { return NULL; }

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_ptr_testcontext_is_null(void *value) { return value == NULL; }

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_testcontext_deref(void *pointer) { return pointer; }

typedef struct { const uint8_t * value; } moon_bindgen_ptr_constptr_byte_t;

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_constptr_byte_new(const uint8_t * initial) {
  moon_bindgen_ptr_constptr_byte_t *slot = (moon_bindgen_ptr_constptr_byte_t *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_ptr_constptr_byte_t));
  slot->value = initial;
  return slot;
}

MOONBIT_FFI_EXPORT
const uint8_t * moon_bindgen_ptr_constptr_byte_get(void *raw_slot) {
  return ((moon_bindgen_ptr_constptr_byte_t *)raw_slot)->value;
}

typedef struct { int32_t * value; } moon_bindgen_ptr_ptr_int_t;

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_int_new(int32_t * initial) {
  moon_bindgen_ptr_ptr_int_t *slot = (moon_bindgen_ptr_ptr_int_t *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_ptr_ptr_int_t));
  slot->value = initial;
  return slot;
}

MOONBIT_FFI_EXPORT
int32_t * moon_bindgen_ptr_ptr_int_get(void *raw_slot) {
  return ((moon_bindgen_ptr_ptr_int_t *)raw_slot)->value;
}

typedef struct { moon_bindgen_c_TestContext * * value; } moon_bindgen_ptr_ptr_ptr_testcontext_t;

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_ptr_testcontext_new(moon_bindgen_c_TestContext * * initial) {
  moon_bindgen_ptr_ptr_ptr_testcontext_t *slot = (moon_bindgen_ptr_ptr_ptr_testcontext_t *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_ptr_ptr_ptr_testcontext_t));
  slot->value = initial;
  return slot;
}

MOONBIT_FFI_EXPORT
moon_bindgen_c_TestContext * * moon_bindgen_ptr_ptr_ptr_testcontext_get(void *raw_slot) {
  return ((moon_bindgen_ptr_ptr_ptr_testcontext_t *)raw_slot)->value;
}

typedef struct { moon_bindgen_c_TestContext * value; } moon_bindgen_ptr_ptr_testcontext_t;

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_ptr_testcontext_new(moon_bindgen_c_TestContext * initial) {
  moon_bindgen_ptr_ptr_testcontext_t *slot = (moon_bindgen_ptr_ptr_testcontext_t *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_ptr_ptr_testcontext_t));
  slot->value = initial;
  return slot;
}

MOONBIT_FFI_EXPORT
moon_bindgen_c_TestContext * moon_bindgen_ptr_ptr_testcontext_get(void *raw_slot) {
  return ((moon_bindgen_ptr_ptr_testcontext_t *)raw_slot)->value;
}

typedef struct { uint64_t value; } moon_bindgen_ptr_uint64_t;

MOONBIT_FFI_EXPORT
void *moon_bindgen_ptr_uint64_new(uint64_t initial) {
  moon_bindgen_ptr_uint64_t *slot = (moon_bindgen_ptr_uint64_t *)moonbit_make_external_object(NULL, sizeof(moon_bindgen_ptr_uint64_t));
  slot->value = initial;
  return slot;
}

MOONBIT_FFI_EXPORT
uint64_t moon_bindgen_ptr_uint64_get(void *raw_slot) {
  return ((moon_bindgen_ptr_uint64_t *)raw_slot)->value;
}

MOONBIT_FFI_EXPORT
void *moon_bindgen_test_context_null(void) {
  return (void *)0;
}

MOONBIT_FFI_EXPORT
int32_t moon_bindgen_test_context_is_null(void *value) {
  return value == (void *)0;
}

extern void test_byte_pointer(const uint8_t * * out, uint64_t * out_len);
MOONBIT_FFI_EXPORT
void moon_bindgen_test_byte_pointer_pointer_out(void *out, void *out_len) {
  test_byte_pointer(&((moon_bindgen_ptr_constptr_byte_t *)out)->value, &((moon_bindgen_ptr_uint64_t *)out_len)->value);
}

extern void test_context_create(moon_bindgen_c_TestContext * * out);
MOONBIT_FFI_EXPORT
void moon_bindgen_test_context_create_pointer_out(void *out) {
  test_context_create(&((moon_bindgen_ptr_ptr_testcontext_t *)out)->value);
}

extern void test_context_pointer_pointer(moon_bindgen_c_TestContext * * * out);
MOONBIT_FFI_EXPORT
void moon_bindgen_test_context_pointer_pointer_pointer_out(void *out) {
  test_context_pointer_pointer(&((moon_bindgen_ptr_ptr_ptr_testcontext_t *)out)->value);
}

extern void test_int_pointer(int32_t * * out);
MOONBIT_FFI_EXPORT
void moon_bindgen_test_int_pointer_pointer_out(void *out) {
  test_int_pointer(&((moon_bindgen_ptr_ptr_int_t *)out)->value);
}

