use crate::model::{Bindings, Diagnostic, DiagnosticLevel, Model, Type};
use crate::{Ownership, Visibility};
use heck::ToSnakeCase;
use std::collections::BTreeSet;

#[allow(clippy::too_many_arguments)]
pub(crate) fn render(
    model: &Model,
    header: &str,
    footer: &str,
    visibility: Visibility,
    function_filter: fn(String) -> bool,
    type_filter: fn(String) -> bool,
    constant_filter: fn(String) -> bool,
    ownership_resolver: &dyn Fn(&str, &str) -> Ownership,
    function_rename: fn(String) -> String,
    type_rename: fn(String) -> String,
    constant_rename: fn(String) -> String,
    prefer_managed_types: bool,
) -> Bindings {
    let mut out = String::from("// Generated by moon-bindgen. Do not edit.\n");
    let mut diagnostics = model.diagnostics.clone();
    let stub = crate::stub::render(
        model,
        visibility,
        function_filter,
        type_filter,
        ownership_resolver,
        function_rename,
        type_rename,
        prefer_managed_types,
    );
    diagnostics.extend(stub.diagnostics.iter().cloned());
    if !header.is_empty() {
        out.push_str(header);
        if !header.ends_with('\n') {
            out.push('\n');
        }
    }
    out.push('\n');
    out.push_str(&stub.moonbit_types);
    let mut opaque = BTreeSet::new();
    let legacy_value_structs = stub
        .value_structs
        .iter()
        .filter(|name| !model.structs[*name].from_bindgen)
        .cloned()
        .collect::<BTreeSet<_>>();
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        for (_, t) in &f.params {
            collect_opaque(t, model, &mut opaque);
        }
        collect_opaque(&f.result, model, &mut opaque);
    }
    for name in &stub.value_structs {
        for field in &model.structs[name].fields {
            collect_opaque(&field.ty, model, &mut opaque);
        }
    }
    for name in opaque {
        if type_filter(name.clone())
            && !model.aliases.contains_key(&name)
            && !model.structs.contains_key(&name)
        {
            emit_external_type(
                &mut out,
                &name,
                "opaque C type",
                &[],
                visibility,
                type_rename,
            );
        }
    }
    for s in model.structs.values() {
        if !type_filter(s.name.clone()) || stub.value_structs.contains(&s.name) {
            continue;
        }
        emit_external_type(
            &mut out,
            &s.name,
            if s.is_union {
                "C union"
            } else {
                "#[repr(C)] struct"
            },
            &s.docs,
            visibility,
            type_rename,
        );
    }
    for (name, alias) in &model.aliases {
        if !type_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_alias_type(name, alias, model, type_filter, type_rename) {
            emit_doc(
                &mut out,
                model.alias_docs.get(name).map(Vec::as_slice).unwrap_or(&[]),
            );
            out.push_str(&format!(
                "{}type {} = {}\n\n",
                visibility.prefix(),
                renamed_type_ident(name, type_rename),
                ty
            ));
        }
    }
    for (name, c) in &model.constants {
        if !constant_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_type(&c.ty, type_rename) {
            emit_doc(&mut out, &c.docs);
            out.push_str(&format!(
                "{}const {} : {} = {}\n\n",
                visibility.prefix(),
                renamed_constant_ident(name, constant_rename),
                ty,
                c.value
            ));
        }
    }
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        if stub.wrapped_symbols.contains(&f.symbol) {
            continue;
        }
        if contains_pointer_to_value_struct(&f.result, &legacy_value_structs)
            || f.params
                .iter()
                .any(|(_, ty)| contains_pointer_to_value_struct(ty, &legacy_value_structs))
        {
            diagnostics.push(warning(
                &f.rust_name,
                "pointer to a struct that is also used by value cannot share the generated value representation",
            ));
            continue;
        }
        if !f.params.iter().all(|(_, ty)| is_direct_ffi_type(ty, model))
            || !is_direct_ffi_type(&f.result, model)
        {
            diagnostics.push(warning(
                &f.rust_name,
                "signature cannot be represented safely by direct MoonBit FFI",
            ));
            continue;
        }
        if f.variadic {
            diagnostics.push(warning(
                &f.rust_name,
                "variadic functions cannot be represented in MoonBit FFI",
            ));
            continue;
        }
        let params: Option<Vec<_>> = f
            .params
            .iter()
            .map(|(n, t)| {
                moon_parameter_type(t, model, type_rename, prefer_managed_types)
                    .map(|ty| (n, ty, needs_ownership_resolved(t, model)))
            })
            .collect();
        let result = moon_result_type(&f.result, model, type_rename);
        let (Some(params), Some(result)) = (params, result) else {
            diagnostics.push(warning(
                &f.rust_name,
                "signature contains an unsupported type",
            ));
            continue;
        };
        let ownerships = params
            .iter()
            .filter(|(_, _, needs_ownership)| *needs_ownership)
            .map(|(name, _, _)| {
                (
                    safe_value_ident(name),
                    ownership_resolver(&f.rust_name, name),
                )
            })
            .collect::<Vec<_>>();
        let borrowed = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Borrow)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        emit_doc(&mut out, &f.docs);
        if !borrowed.is_empty() {
            out.push_str(&format!("#borrow({})\n", borrowed.join(", ")));
        }
        let owned = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Owned)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !owned.is_empty() {
            out.push_str(&format!("#owned({})\n", owned.join(", ")));
        }
        out.push_str(&format!(
            "{}extern \"c\" fn {}(",
            visibility.prefix(),
            renamed_value_ident(&f.rust_name, function_rename)
        ));
        for (i, (name, ty, _)) in params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{} : {}", safe_value_ident(name), ty));
        }
        out.push(')');
        if result != "Unit" {
            out.push_str(&format!(" -> {result}"));
        }
        out.push_str(&format!(" = \"{}\"\n\n", f.symbol));
    }
    out.push_str(&stub.moonbit_functions);
    if !footer.is_empty() {
        if !out.ends_with("\n\n") {
            out.push('\n');
        }
        out.push_str(footer);
    }
    let trimmed_len = out.trim_end().len();
    out.truncate(trimmed_len);
    out.push('\n');
    Bindings::new(out, stub.c_source, diagnostics)
}

fn moon_alias_type(
    name: &str,
    alias: &Type,
    model: &Model,
    type_filter: fn(String) -> bool,
    type_rename: fn(String) -> String,
) -> Option<String> {
    let emitted_name = renamed_type_ident(name, type_rename);
    let mut current = alias;
    let mut seen = BTreeSet::new();
    loop {
        let ty = moon_type(current, type_rename)?;
        let Type::Path(path) = current else {
            return (ty != emitted_name).then_some(ty);
        };
        let target = path.rsplit("::").next()?;
        let should_resolve = ty == emitted_name
            || (!type_filter(target.to_owned()) && model.aliases.contains_key(target));
        if !should_resolve {
            return Some(ty);
        }
        if !seen.insert(target) {
            return None;
        }
        current = model.aliases.get(target)?;
    }
}

fn emit_external_type(
    out: &mut String,
    name: &str,
    note: &str,
    docs: &[String],
    visibility: Visibility,
    type_rename: fn(String) -> String,
) {
    emit_doc(out, docs);
    out.push_str(&format!(
        "#external\n{}type {} // {}\n\n",
        visibility.prefix(),
        renamed_type_ident(name, type_rename),
        note
    ));
}

pub(crate) fn emit_doc(out: &mut String, docs: &[String]) {
    out.push_str("///|\n");
    for line in docs {
        if line.is_empty() {
            out.push_str("///\n");
        } else {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
}

fn moon_type(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    moon_type_config(ty, type_rename)
}

fn moon_type_config(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    match ty {
        Type::Unit => Some("Unit".into()),
        Type::Path(p) => Some(match p.rsplit("::").next()? {
            "i8" | "u8" => "Byte".into(),
            "i16" | "u16" | "i32" => "Int".into(),
            "u32" => "UInt".into(),
            "i64" => "Int64".into(),
            "u64" => "UInt64".into(),
            "f32" | "c_float" => "Float".into(),
            "f64" | "c_double" => "Double".into(),
            "bool" => "Bool".into(),
            "c_void" => "Unit".into(),
            name if c_scalar_moon_type(name).is_some() => c_scalar_moon_type(name)?.into(),
            other => renamed_type_ident(other, type_rename),
        }),
        Type::Pointer { inner, mutable } => Some(format!(
            "@c.{}[{}]",
            if *mutable {
                "Pointer"
            } else {
                "ReadOnlyPointer"
            },
            moon_pointee_type(inner, type_rename)?
        )),
        Type::Array { inner, .. } => {
            moon_type_config(inner, type_rename).map(|t| format!("FixedArray[{t}]"))
        }
        Type::FunctionPointer {
            params,
            result,
            variadic,
            nullable,
        } => {
            if *variadic {
                return None;
            }
            let params = params
                .iter()
                .map(|ty| moon_type_config(ty, type_rename))
                .collect::<Option<Vec<_>>>()?
                .join(", ");
            let ty = format!(
                "FuncRef[({params}) -> {}]",
                moon_type_config(result, type_rename)?
            );
            Some(if *nullable { format!("{ty}?") } else { ty })
        }
        Type::Unsupported => None,
    }
}

fn moon_pointee_type(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    match ty {
        Type::Path(path) => {
            let name = path.rsplit("::").next()?;
            Some(
                c_marker_type(name)
                    .map(str::to_owned)
                    .unwrap_or_else(|| renamed_type_ident(name, type_rename)),
            )
        }
        _ => moon_type_config(ty, type_rename),
    }
}

pub(crate) fn c_marker_type(name: &str) -> Option<&'static str> {
    Some(match name {
        "i8" => "@c.CInt8",
        "u8" => "@c.CUInt8",
        "i16" => "@c.CInt16",
        "u16" => "@c.CUInt16",
        "i32" => "@c.CInt32",
        "u32" => "@c.CUInt32",
        "i64" => "@c.CInt64",
        "u64" => "@c.CUInt64",
        "isize" | "ptrdiff_t" => "@c.CPtrDiff",
        "usize" | "size_t" => "@c.CSize",
        "intptr_t" => "@c.CIntPtr",
        "uintptr_t" => "@c.CUIntPtr",
        "bool" => "@c.CBool",
        "c_char" => "@c.CChar",
        "c_schar" => "@c.CSignedChar",
        "c_uchar" => "@c.CUnsignedChar",
        "c_short" => "@c.CShort",
        "c_ushort" => "@c.CUnsignedShort",
        "c_int" => "@c.CInt",
        "c_uint" => "@c.CUnsignedInt",
        "c_long" => "@c.CLong",
        "c_ulong" => "@c.CUnsignedLong",
        "c_longlong" => "@c.CLongLong",
        "c_ulonglong" => "@c.CUnsignedLongLong",
        "c_float" | "f32" => "@c.CFloat",
        "c_double" | "f64" => "@c.CDouble",
        "c_void" => "@c.CVoid",
        _ => return None,
    })
}

pub(crate) fn c_scalar_moon_type(name: &str) -> Option<&'static str> {
    Some(match name {
        "isize" | "ptrdiff_t" => "@c.CPtrDiff",
        "usize" | "size_t" => "@c.CSize",
        "intptr_t" => "@c.CIntPtr",
        "uintptr_t" => "@c.CUIntPtr",
        "c_char" => "@c.CChar",
        "c_schar" => "@c.CSignedChar",
        "c_uchar" => "@c.CUnsignedChar",
        "c_short" => "@c.CShort",
        "c_ushort" => "@c.CUnsignedShort",
        "c_int" => "@c.CInt",
        "c_uint" => "@c.CUnsignedInt",
        "c_long" => "@c.CLong",
        "c_ulong" => "@c.CUnsignedLong",
        "c_longlong" => "@c.CLongLong",
        "c_ulonglong" => "@c.CUnsignedLongLong",
        _ => return None,
    })
}
fn needs_ownership(t: &Type) -> bool {
    matches!(
        t,
        Type::Pointer { .. } | Type::Array { .. } | Type::FunctionPointer { .. }
    )
}

fn needs_ownership_resolved(t: &Type, model: &Model) -> bool {
    match t {
        Type::Path(path) => model
            .aliases
            .get(path.rsplit("::").next().unwrap_or(path))
            .is_some_and(|alias| needs_ownership_resolved(alias, model)),
        _ => needs_ownership(t),
    }
}

fn is_direct_ffi_type(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Unit => true,
        Type::Path(path) => {
            let name = path.rsplit("::").next().unwrap_or(path);
            if primitive_moon_type(path).is_some() || name == "c_void" {
                return true;
            }
            if model.structs.contains_key(name) {
                return false;
            }
            model
                .aliases
                .get(name)
                .is_some_and(|alias| is_direct_ffi_type(alias, model))
        }
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::Array { .. } => false,
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unsupported => false,
    }
}

fn is_pointer_pointee(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Path(_) => true,
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unit | Type::Array { .. } | Type::Unsupported => false,
    }
}
fn moon_parameter_type(
    ty: &Type,
    model: &Model,
    type_rename: fn(String) -> String,
    prefer_managed_types: bool,
) -> Option<String> {
    if prefer_managed_types && let Some(ty) = managed_byte_pointer_type(ty, model) {
        return Some(ty.into());
    }
    moon_ffi_type(ty, model, type_rename)
}

pub(crate) fn managed_byte_pointer_type<'a>(ty: &Type, model: &Model) -> Option<&'a str> {
    let Type::Pointer { inner, mutable } = resolve_alias_for_managed_type(ty, model) else {
        return None;
    };
    let Type::Path(path) = resolve_alias_for_managed_type(inner, model) else {
        return None;
    };
    match path.rsplit("::").next()? {
        "i8" | "u8" | "c_char" | "c_schar" | "c_uchar" => Some(if *mutable {
            "FixedArray[Byte]"
        } else {
            "Bytes"
        }),
        _ => None,
    }
}

fn resolve_alias_for_managed_type<'a>(ty: &'a Type, model: &'a Model) -> &'a Type {
    let mut current = ty;
    let mut seen = BTreeSet::new();
    while let Type::Path(path) = current {
        let name = path.rsplit("::").next().unwrap_or(path);
        if !seen.insert(name) {
            break;
        }
        let Some(alias) = model.aliases.get(name) else {
            break;
        };
        current = alias;
    }
    current
}

fn moon_result_type(ty: &Type, model: &Model, type_rename: fn(String) -> String) -> Option<String> {
    moon_ffi_type(ty, model, type_rename)
}

fn moon_ffi_type(ty: &Type, model: &Model, type_rename: fn(String) -> String) -> Option<String> {
    match ty {
        Type::Pointer { inner, mutable } => Some(format!(
            "@c.{}[{}]",
            if *mutable {
                "Pointer"
            } else {
                "ReadOnlyPointer"
            },
            moon_ffi_pointee_type(inner, model, type_rename)?
        )),
        _ => moon_type_config(ty, type_rename),
    }
}

fn moon_ffi_pointee_type(
    ty: &Type,
    model: &Model,
    type_rename: fn(String) -> String,
) -> Option<String> {
    match ty {
        Type::Path(path) => {
            let original = path.rsplit("::").next()?;
            let mut current = ty;
            let mut seen = BTreeSet::new();
            while let Type::Path(path) = current {
                let name = path.rsplit("::").next()?;
                if !seen.insert(name) {
                    break;
                }
                let Some(alias) = model.aliases.get(name) else {
                    return Some(
                        c_marker_type(name)
                            .map(str::to_owned)
                            .unwrap_or_else(|| renamed_type_ident(original, type_rename)),
                    );
                };
                current = alias;
            }
            moon_ffi_pointee_type(current, model, type_rename)
        }
        Type::Pointer { .. } => moon_ffi_type(ty, model, type_rename),
        _ => moon_type_config(ty, type_rename),
    }
}
fn collect_opaque(t: &Type, model: &Model, out: &mut BTreeSet<String>) {
    match t {
        Type::Pointer { inner, .. } => {
            if let Type::Path(p) = inner.as_ref() {
                let n = p.rsplit("::").next().unwrap();
                if n != "c_void"
                    && !is_primitive(n)
                    && !model.structs.contains_key(n)
                    && !model.aliases.contains_key(n)
                {
                    out.insert(n.into());
                }
            } else {
                collect_opaque(inner, model, out);
            }
        }
        Type::Array { inner, .. } => collect_opaque(inner, model, out),
        Type::FunctionPointer { params, result, .. } => {
            for param in params {
                collect_opaque(param, model, out);
            }
            collect_opaque(result, model, out);
        }
        _ => {}
    }
}
fn contains_pointer_to_value_struct(t: &Type, value_structs: &BTreeSet<String>) -> bool {
    match t {
        Type::Pointer { inner, .. } => match inner.as_ref() {
            Type::Path(path) => value_structs.contains(path.rsplit("::").next().unwrap_or(path)),
            other => contains_pointer_to_value_struct(other, value_structs),
        },
        Type::Array { inner, .. } => contains_pointer_to_value_struct(inner, value_structs),
        Type::FunctionPointer { params, result, .. } => {
            params
                .iter()
                .any(|param| contains_pointer_to_value_struct(param, value_structs))
                || contains_pointer_to_value_struct(result, value_structs)
        }
        _ => false,
    }
}
fn is_primitive(s: &str) -> bool {
    matches!(
        s,
        "i8" | "u8"
            | "i16"
            | "u16"
            | "i32"
            | "u32"
            | "i64"
            | "u64"
            | "isize"
            | "usize"
            | "f32"
            | "f64"
            | "bool"
            | "c_char"
            | "c_schar"
            | "c_uchar"
            | "c_short"
            | "c_ushort"
            | "c_int"
            | "c_uint"
            | "c_long"
            | "c_ulong"
            | "c_longlong"
            | "c_ulonglong"
            | "size_t"
            | "ptrdiff_t"
            | "intptr_t"
            | "uintptr_t"
            | "c_float"
            | "c_double"
            | "c_void"
    )
}

fn primitive_moon_type(path: &str) -> Option<&'static str> {
    let name = path.rsplit("::").next()?;
    match name {
        "i8" | "u8" => Some("Byte"),
        "i16" | "u16" | "i32" => Some("Int"),
        "u32" => Some("UInt"),
        "i64" => Some("Int64"),
        "u64" => Some("UInt64"),
        "f32" | "c_float" => Some("Float"),
        "f64" | "c_double" => Some("Double"),
        "bool" => Some("Bool"),
        _ => c_scalar_moon_type(name),
    }
}
fn warning(item: &str, message: &str) -> Diagnostic {
    Diagnostic {
        level: DiagnosticLevel::Warning,
        item: item.into(),
        message: message.into(),
    }
}
fn safe_ident(s: &str) -> String {
    crate::ident::safe_moonbit_ident(s)
}

fn safe_value_ident(s: &str) -> String {
    let raw = s.replace("r#", "").to_snake_case();
    if raw.is_empty() {
        return "value".into();
    }
    safe_ident(&raw)
}

fn renamed_value_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_type_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_constant_ident(s: &str, rename: fn(String) -> String) -> String {
    let name = rename(s.to_owned());
    if name.is_empty() {
        "CONSTANT".into()
    } else {
        safe_ident(&name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{model::Model, parse};
    use heck::{ToShoutySnakeCase, ToUpperCamelCase};
    fn default_function_rename(name: String) -> String {
        name.to_snake_case()
    }
    fn default_type_rename(name: String) -> String {
        name.to_upper_camel_case()
    }
    fn default_constant_rename(name: String) -> String {
        name.to_shouty_snake_case()
    }
    #[test]
    fn generates_ffi() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Point { pub x:i32,pub y:i32 }
pub const ANSWER:u32=42;
unsafe extern "C" { pub fn c_move(p:*mut Point,n:usize)->i32; }
#[unsafe(no_mangle)] pub extern "C" fn rust_ping(value:u64)->bool { true }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "// custom footer",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("#external\ntype Point"));
        assert!(
            b.moonbit_source()
                .contains("fn Point::new(x : Int, y : Int) -> Point")
        );
        assert!(
            b.c_stub_source()
                .contains("void *moon_bindgen_point_new(int32_t x, int32_t y)")
        );
        assert!(
            b.moonbit_source()
                .contains("fn Point::get_x(self : Point) -> Int")
        );
        assert!(
            b.moonbit_source()
                .contains("fn Point::set_y(self : Point, value : Int) -> Unit")
        );
        assert!(
            b.c_stub_source()
                .contains("int32_t moon_bindgen_point_x_get(void *self)")
        );
        assert!(b.moonbit_source().contains("#borrow(p)"));
        assert!(
            b.moonbit_source()
                .contains("fn c_move(p : @c.Pointer[Point], n : @c.CSize) -> Int")
        );
        assert!(
            b.moonbit_source()
                .contains("fn rust_ping(value : UInt64) -> Bool")
        );
        assert!(b.moonbit_source().ends_with("// custom footer\n"));
    }

    #[test]
    fn generates_function_pointer_aliases_and_direct_callbacks() {
        let f = syn::parse_file(
            r#"
pub type Compare = ::std::option::Option<unsafe extern "C" fn(a: i32, b: i32) -> i32>;
unsafe extern "C" {
  pub fn sort_items(compare: Compare);
  pub fn get_callback() -> unsafe extern "C" fn(value: u64);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(
            b.moonbit_source()
                .contains("type Compare = FuncRef[(Int, Int) -> Int]?")
        );
        assert!(b.moonbit_source().contains("#borrow(compare)"));
        assert!(
            b.moonbit_source()
                .contains("fn sort_items(compare : Compare)")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_callback() -> FuncRef[(UInt64) -> Unit]")
        );
        assert!(b.diagnostics().is_empty());
    }

    #[test]
    fn emits_byte_pointers_through_the_c_package() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn connect(server_name: *const ::std::os::raw::c_char, id: *const u8);
                pub fn optional_data() -> *const u8;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(
            b.moonbit_source()
                .contains("fn connect(server_name : @c.ReadOnlyPointer[@c.CChar], id : @c.ReadOnlyPointer[@c.CUInt8])")
        );
        assert!(b.moonbit_source().contains("#borrow(server_name, id)"));
        assert!(
            b.moonbit_source()
                .contains("fn optional_data() -> @c.ReadOnlyPointer[@c.CUInt8]")
        );
    }

    #[test]
    fn forward_declares_structs_referenced_by_pointer_fields() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Node { pub next: *const Node, pub value: i32 }
unsafe extern "C" { pub fn visit(node: *const Node); }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        let c = b.c_stub_source();
        let declaration = "typedef struct moon_bindgen_c_Node moon_bindgen_c_Node;";
        let definition = "struct moon_bindgen_c_Node {";
        assert!(c.find(declaration).unwrap() < c.find(definition).unwrap());
        assert!(c.contains("return (void *)value->next;"));
    }

    #[test]
    fn normalizes_c_function_names_and_groups_borrows() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_copy(src: *const i8, dst: *mut i8) -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("#borrow(src, dst)"));
        assert!(b.moonbit_source().contains("fn lz4_copy("));
        assert!(b.moonbit_source().contains("= \"LZ4_copy\""));
    }

    #[test]
    fn emits_public_types_and_functions_when_configured() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Context { _private: [u8; 0] }
pub type Count = u32;
pub const DEFAULT_COUNT: Count = 3;
unsafe extern "C" { pub fn library_count(context: *mut Context) -> Count; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("#external\npub type Context"));
        assert!(b.moonbit_source().contains("pub type Count = UInt"));
        assert!(
            b.moonbit_source()
                .contains("pub const DEFAULT_COUNT : Count = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("pub extern \"c\" fn library_count")
        );
    }

    #[test]
    fn filters_methods_using_original_rust_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_keep() -> i32;
                pub fn XXH_drop() -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |name| name.starts_with("LZ4_"),
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("fn lz4_keep"));
        assert!(!b.moonbit_source().contains("xxh_drop"));
        assert!(!b.moonbit_source().contains("XXH_drop"));
    }

    #[test]
    fn escapes_all_moonbit_keywords_in_generated_value_names() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct ReservedFields {
  pub readonly: i32,
  pub opaque: i32,
}
unsafe extern "C" {
  pub fn guard(module: i32, value: ReservedFields);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("readonly_ : Int"));
        assert!(moon.contains("opaque_ : Int"));
        assert!(moon.contains("pub fn guard_(module_ : Int, value : ReservedFields)"));
        assert!(!moon.contains("pub fn guard("));
        assert!(b.c_stub_source().contains("int32_t readonly;"));
        assert!(b.c_stub_source().contains("int32_t opaque;"));
    }

    #[test]
    fn filters_types_and_constants_by_original_rust_names() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct KeepType { value: i32 }
#[repr(C)] pub struct DropType { value: i32 }
pub type KeepAlias = u32;
pub type DropAlias = u32;
pub const KEEP_CONST: u32 = 1;
pub const DROP_CONST: u32 = 2;
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |name| name.starts_with("Keep"),
            |name| name.starts_with("KEEP"),
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("type KeepType"));
        assert!(b.moonbit_source().contains("type KeepAlias"));
        assert!(!b.moonbit_source().contains("DropType"));
        assert!(!b.moonbit_source().contains("DropAlias"));
        assert!(b.moonbit_source().contains("const KEEP_CONST"));
        assert!(!b.moonbit_source().contains("DROP_CONST"));
    }

    #[test]
    fn normalizes_lowercase_types_and_scalar_pointers() {
        let f = syn::parse_file(
            r#"
pub type int_fast16_t = i16;
pub type stream_t = stream_u;
#[repr(C)] pub union stream_u { value: i32 }
unsafe extern "C" {
  pub fn update(value: *mut ::std::os::raw::c_int, stream: *mut stream_t);
  pub fn update_fast(value: *mut int_fast16_t);
  pub fn get_context(value: *mut *mut Context);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("type IntFast16T = Int"));
        assert!(b.moonbit_source().contains("type StreamT = StreamU"));
        assert_eq!(b.moonbit_source().matches("type StreamT").count(), 1);
        assert!(
            b.moonbit_source()
                .contains("fn update(value : @c.Pointer[@c.CInt], stream : @c.Pointer[StreamT])")
        );
        assert!(!b.moonbit_source().contains("type c_int"));
        assert!(
            b.moonbit_source()
                .contains("fn update_fast(value : @c.Pointer[@c.CInt16])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_context(value : @c.Pointer[@c.Pointer[Context]])")
        );
        assert!(b.c_stub_source().is_empty());
        assert!(!b.c_stub_source().contains("moon_bindgen_ptr_ptr_context"));
    }

    #[test]
    fn resolves_aliases_that_collapse_to_the_same_moonbit_name() {
        let f = syn::parse_file(
            r#"
pub type __int16_t = ::std::os::raw::c_short;
pub type __int8_t = i8;
pub type __int32_t = i32;
pub type __int64_t = i64;
pub type int_least8_t = __int8_t;
pub type int_least16_t = __int16_t;
pub type int_least32_t = __int32_t;
pub type int_least64_t = __int64_t;
pub type __uint8_t = u8;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __uint32_t = u32;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type uint_least8_t = __uint8_t;
pub type uint_least16_t = __uint16_t;
pub type uint_least32_t = __uint32_t;
pub type uint_least64_t = __uint64_t;
pub type uintmax_t = __uint64_t;
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |name| !name.starts_with('_'),
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(
            b.moonbit_source()
                .contains("pub type IntLeast16T = @c.CShort")
        );
        assert!(b.moonbit_source().contains("pub type IntLeast8T = Byte"));
        assert!(b.moonbit_source().contains("pub type IntLeast32T = Int"));
        assert!(b.moonbit_source().contains("pub type IntLeast64T = Int64"));
        assert!(b.moonbit_source().contains("pub type UintLeast8T = Byte"));
        assert!(
            b.moonbit_source()
                .contains("pub type UintLeast16T = @c.CUnsignedShort")
        );
        assert!(b.moonbit_source().contains("pub type UintLeast32T = UInt"));
        assert!(
            b.moonbit_source()
                .contains("pub type UintLeast64T = @c.CUnsignedLong")
        );
        assert!(
            b.moonbit_source()
                .contains("pub type UintmaxT = @c.CUnsignedLong")
        );
        assert!(!b.moonbit_source().contains("IntLeast16T = IntLeast16T"));
        assert!(!b.moonbit_source().contains("UintmaxT = UintmaxT"));
    }

    #[test]
    fn resolves_parameter_ownership_with_original_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn register_data(kept: *mut u8, temporary: *const u8, raw: *mut u8);
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|function, parameter| match (function, parameter) {
                ("register_data", "kept") => Ownership::Owned,
                _ => Ownership::Borrow,
            },
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("#owned(kept)"));
        assert!(b.moonbit_source().contains("#borrow(temporary, raw)"));
        assert!(!b.moonbit_source().contains("#owned(raw)"));
    }

    #[test]
    fn generates_struct_value_stubs_and_skips_remaining_unsupported_signatures() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Value { field: i32 }
unsafe extern "C" {
  pub fn by_value(value: Value) -> Value;
  pub fn double_pointer(value: *mut *mut i32);
  pub fn context_pointer(value: *mut *mut Context);
  pub fn triple_pointer(value: *mut *mut *mut Context);
  pub fn raw_double_pointer(value: *mut *mut ::std::ffi::c_void);
  pub fn byte_double_pointer(value: *mut *mut u8);
  pub fn nullable(value: Option<*mut Value>);
  pub fn supported(value: *mut Value);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("struct Value"));
        assert!(b.moonbit_source().contains("fn by_value"));
        assert!(b.c_stub_source().contains("moon_bindgen_by_value"));
        assert!(b.c_stub_source().contains("moonbit_make_bytes"));
        assert!(
            b.moonbit_source()
                .contains("fn double_pointer(value : @c.Pointer[@c.Pointer[@c.CInt32]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn context_pointer(value : @c.Pointer[@c.Pointer[Context]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn triple_pointer(value : @c.Pointer[@c.Pointer[@c.Pointer[Context]]])")
        );
        assert!(!b.moonbit_source().contains("#external\ntype Ptr[T]"));
        assert!(!b.moonbit_source().contains("moon_bindgen_ptr_context_null"));
        assert!(
            !b.c_stub_source()
                .contains("moon_bindgen_ptr_ptr_context_null")
        );
        assert!(
            b.moonbit_source()
                .contains("fn raw_double_pointer(value : @c.Pointer[@c.Pointer[@c.CVoid]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn byte_double_pointer(value : @c.Pointer[@c.Pointer[@c.CUInt8]])")
        );
        assert!(!b.moonbit_source().contains("fn nullable"));
        assert!(!b.moonbit_source().contains("fn supported"));
        assert_eq!(b.diagnostics().len(), 2);
    }

    #[test]
    fn generates_nested_struct_dependencies_and_fixed_array_marshalling() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Inner { value: i32, bytes: [u8; 4] }
#[repr(C)] pub struct Outer { inner: Inner, enabled: bool }
#[repr(C)] pub struct PointerHolder { value: *mut *mut i32 }
unsafe extern "C" {
  pub fn round_trip(value: Outer) -> Outer;
  pub fn consume_pointer_holder(value: PointerHolder);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("pub(all) struct Inner"));
        assert!(
            b.moonbit_source()
                .contains("value : @c.Pointer[@c.Pointer[@c.CInt32]]")
        );
        assert!(b.c_stub_source().contains("int32_t * * value_value"));
        assert!(b.moonbit_source().contains("pub(all) struct Outer"));
        assert!(
            b.moonbit_source()
                .contains("value.inner.bytes.length() != 4")
        );
        assert!(
            b.c_stub_source()
                .contains("memcpy(moon_bindgen_arg_value.inner.bytes")
        );
        assert!(
            b.c_stub_source()
                .contains("moonbit_make_bytes((int32_t)sizeof(result), 0)")
        );
    }

    #[test]
    fn preserves_bindgen_opaque_structs_as_external_types() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct sockaddr_storage {
  pub _bindgen_opaque_blob: [u64; 16],
}
#[repr(C)] pub struct timespec {
  pub __bindgen_opaque_blob: [u64; 2],
}
#[repr(C)] pub struct quiche_send_info {
  pub to: sockaddr_storage,
  pub at: timespec,
}
unsafe extern "C" {
  pub fn inspect_address(value: *const sockaddr_storage);
  pub fn inspect_time(value: *const timespec);
  pub fn send(info: quiche_send_info);
  pub fn take_address(value: sockaddr_storage);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        let moon = b.moonbit_source();
        assert!(moon.contains("#external\npub type SockaddrStorage"));
        assert!(moon.contains("#external\npub type Timespec"));
        assert!(moon.contains("#external\npub type QuicheSendInfo"));
        assert!(moon.contains(
            "pub extern \"c\" fn inspect_address(value : @c.ReadOnlyPointer[SockaddrStorage])"
        ));
        assert!(
            moon.contains("pub extern \"c\" fn inspect_time(value : @c.ReadOnlyPointer[Timespec])")
        );
        assert!(!moon.contains("fn SockaddrStorage::new"));
        assert!(!moon.contains("fn Timespec::new"));
        assert!(!moon.contains("fn QuicheSendInfo::new"));
        assert!(!moon.contains("fn send"));
        assert!(!moon.contains("fn take_address"));
        assert!(b.c_stub_source().is_empty());
        assert_eq!(b.diagnostics().len(), 4);
        assert!(
            b.diagnostics()
                .iter()
                .all(|diagnostic| matches!(diagnostic.item.as_str(), "send" | "take_address"))
        );
    }

    #[test]
    fn generates_borrowed_getters_for_pointer_returned_bindgen_structs() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct CURL {
  pub _bindgen_opaque_blob: [u8; 1usize],
}
#[repr(C)]
pub union CURLMsgData {
  pub whatever: *mut ::std::ffi::c_void,
  pub result: i32,
}
#[repr(C)]
pub struct CURLMsg {
  pub msg: i32,
  pub easy_handle: *mut CURL,
  pub data: CURLMsgData,
}
#[repr(C)]
pub struct CURLVersion {
  pub version_num: u32,
}
#[repr(C)]
pub struct MutableValue {
  pub value: i32,
}
unsafe extern "C" {
  pub fn curl_multi_info_read() -> *mut CURLMsg;
  pub fn curl_version_info() -> *const CURLVersion;
  pub fn mutable_curl_version_info() -> *mut CURLVersion;
  pub fn mutable_value() -> *mut MutableValue;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(!moon.contains("type CurlMsgPointer"));
        assert!(moon.contains("pub extern \"c\" fn curl_multi_info_read() -> @c.Pointer[CurlMsg]"));
        assert!(moon.contains(
            "pub extern \"c\" fn curl_version_info() -> @c.ReadOnlyPointer[CurlVersion]"
        ));
        assert!(
            moon.contains(
                "pub fn CurlMsg::get_msg_at(pointer : @c.ReadOnlyPointer[CurlMsg]) -> Int"
            )
        );
        assert!(moon.contains(
            "pub fn CurlMsg::get_easy_handle_at(pointer : @c.ReadOnlyPointer[CurlMsg]) -> @c.Pointer[Curl]"
        ));
        assert!(moon.contains(
            "pub fn CurlMsg::get_data_result_at(pointer : @c.ReadOnlyPointer[CurlMsg]) -> Int"
        ));
        assert!(moon.contains(
            "pub fn CurlMsg::set_msg_at(pointer : @c.Pointer[CurlMsg], value : Int) -> Unit"
        ));
        assert!(moon.contains(
            "pub fn CurlMsg::set_data_result_at(pointer : @c.Pointer[CurlMsg], value : Int) -> Unit"
        ));
        assert!(moon.contains(
            "pub fn CurlVersion::get_version_num_at(pointer : @c.ReadOnlyPointer[CurlVersion]) -> UInt"
        ));
        assert!(moon.contains(
            "pub fn CurlVersion::set_version_num_at(pointer : @c.Pointer[CurlVersion], value : UInt) -> Unit"
        ));
        assert!(moon.contains(
            "pub fn MutableValue::get_value_at(pointer : @c.ReadOnlyPointer[MutableValue]) -> Int"
        ));
        assert!(moon.contains(
            "pub fn MutableValue::set_value_at(pointer : @c.Pointer[MutableValue], value : Int) -> Unit"
        ));
        assert!(!moon.contains("::as_pointer"));
        assert!(!moon.contains("::from_pointer"));
        assert!(moon.contains("pub fn CurlVersion::get_version_num(self : CurlVersion) -> UInt"));
        assert!(moon.contains("pub fn MutableValue::get_value(self : MutableValue) -> Int"));
        assert!(
            moon.contains(
                "pub fn MutableValue::set_value(self : MutableValue, value : Int) -> Unit"
            )
        );
        assert!(moon.contains("#borrow(pointer)"));

        let stub = b.c_stub_source();
        assert!(stub.contains("return (int32_t)value->msg;"));
        assert!(stub.contains("return (void *)value->easy_handle;"));
        assert!(stub.contains("return (int32_t)value->data.result;"));
        assert!(stub.contains("value->msg = field;"));
        assert!(stub.contains("value->data.result = field;"));
        assert!(stub.contains("_version_num_pointer_get"));
    }

    #[test]
    fn c_package_pointers_retain_null_values_directly() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Context { _private: [u8; 0] }
unsafe extern "C" {
  pub fn get_context() -> *mut Context;
  pub fn set_context(value: *mut Context);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        let moon = b.moonbit_source();
        assert!(moon.contains("pub extern \"c\" fn get_context() -> @c.Pointer[Context]"));
        assert!(moon.contains("pub extern \"c\" fn set_context(value : @c.Pointer[Context])"));
        assert!(!moon.contains("Context?"));
    }

    #[test]
    fn renames_functions_types_constants_and_type_references() {
        let f = syn::parse_file(
            r#"
pub type LIB_count_t = u32;
pub const LIB_DEFAULT_COUNT: LIB_count_t = 3;
unsafe extern "C" { pub fn LIB_getCount() -> LIB_count_t; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let function_rename =
            |name: String| name.strip_prefix("LIB_").unwrap_or(&name).to_snake_case();
        let type_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_upper_camel_case()
        };
        let constant_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_shouty_snake_case()
        };
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            function_rename,
            type_rename,
            constant_rename,
            false,
        );
        assert!(b.moonbit_source().contains("type CountT = UInt"));
        assert!(
            b.moonbit_source()
                .contains("const DEFAULT_COUNT : CountT = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_count() -> CountT = \"LIB_getCount\"")
        );
    }

    #[test]
    fn preserves_platform_dependent_c_scalar_types() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct PlatformScalars {
  pub signed_long: ::std::os::raw::c_long,
  pub unsigned_long: ::std::os::raw::c_ulong,
  pub size: size_t,
  pub difference: ptrdiff_t,
  pub signed_pointer: intptr_t,
  pub unsigned_pointer: uintptr_t,
}
unsafe extern "C" {
  pub fn consume_platform_scalars(value: PlatformScalars) -> PlatformScalars;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("signed_long : @c.CLong"));
        assert!(moon.contains("unsigned_long : @c.CUnsignedLong"));
        assert!(moon.contains("size : @c.CSize"));
        assert!(moon.contains("difference : @c.CPtrDiff"));
        assert!(moon.contains("signed_pointer : @c.CIntPtr"));
        assert!(moon.contains("unsigned_pointer : @c.CUIntPtr"));

        let stub = b.c_stub_source();
        assert!(stub.contains("#include <stddef.h>"));
        assert!(stub.contains("long signed_long;"));
        assert!(stub.contains("unsigned long unsigned_long;"));
        assert!(stub.contains("size_t size;"));
        assert!(stub.contains("ptrdiff_t difference;"));
        assert!(stub.contains("intptr_t signed_pointer;"));
        assert!(stub.contains("uintptr_t unsigned_pointer;"));
        assert!(!stub.contains("int64_t signed_long;"));
        assert!(!stub.contains("uint64_t unsigned_long;"));
    }

    #[test]
    fn bindgen_struct_values_use_the_native_c_layout() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct PlatformInfo {
  pub _bindgen_opaque_blob: [u8; 136],
}
unsafe extern "C" {
  pub fn round_trip_platform_info(value: PlatformInfo) -> PlatformInfo;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("#external\npub type PlatformInfo // native C layout"));
        assert!(
            moon.contains("pub fn round_trip_platform_info(value : PlatformInfo) -> PlatformInfo")
        );
        assert!(!moon.contains("pub(all) struct PlatformInfo"));
        assert!(!moon.contains("PlatformInfo::new"));

        let stub = b.c_stub_source();
        assert!(stub.contains("typedef PlatformInfo moon_bindgen_c_PlatformInfo;"));
        assert!(!stub.contains("struct moon_bindgen_c_PlatformInfo {"));
        assert!(stub.contains("*(moon_bindgen_c_PlatformInfo *)value"));
        assert!(stub.contains("sizeof(moon_bindgen_c_PlatformInfo)"));
        assert!(stub.contains("*result = round_trip_platform_info("));
    }

    #[test]
    fn constructs_bindgen_structs_that_are_passed_by_value() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct Vector2 {
  pub x: f32,
  pub y: f32,
}
unsafe extern "C" {
  pub fn normalize(value: Vector2) -> Vector2;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("pub fn Vector2::new(x : Float, y : Float) -> Vector2"));
        assert!(moon.contains("pub fn Vector2::get_x(self : Vector2) -> Float"));
        assert!(moon.contains("pub fn Vector2::set_x(self : Vector2, value : Float) -> Unit"));
        assert!(b.c_stub_source().contains("moon_bindgen_vector2_new"));
        assert!(b.c_stub_source().contains("moon_bindgen_vector2_x_get"));
    }

    #[test]
    fn restores_bindgen_c_field_names_and_declares_pointer_field_types() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct AutomationEvent {
  pub frame: u32,
  pub type_: u32,
}
#[repr(C)]
pub struct Transform {
  pub translation: [f32; 3usize],
}
#[repr(C)]
pub struct ModelAnimation {
  pub bone_count: i32,
  pub frame_poses: *mut *mut Transform,
}
unsafe extern "C" {
  pub fn consume_event(value: *const AutomationEvent);
  pub fn consume_animation(value: *const ModelAnimation);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let stub = b.c_stub_source();
        assert!(stub.contains("value->type = type_;"));
        assert!(stub.contains("return value->type;"));
        assert!(!stub.contains("value->type_"));
        assert!(stub.contains("typedef Transform moon_bindgen_c_Transform;"));
        assert!(stub.contains("moon_bindgen_c_Transform * * frame_poses"));
    }

    #[test]
    fn preserves_bindgen_struct_pointer_parameters() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct SockAddr {
  pub _bindgen_opaque_blob: [u8; 128],
}
#[repr(C)]
pub struct RecvInfo {
  pub from: *mut SockAddr,
  pub from_len: u32,
  pub to: *mut SockAddr,
  pub to_len: u32,
}
unsafe extern "C" {
  pub fn receive_packet(info: *const RecvInfo) -> i32;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("pub fn RecvInfo::new("));
        assert!(moon.contains(
            "pub extern \"c\" fn receive_packet(info : @c.ReadOnlyPointer[RecvInfo]) -> Int = \"receive_packet\""
        ));
        assert!(!moon.contains("pub fn SockAddr::new("));

        let stub = b.c_stub_source();
        assert!(stub.contains("typedef RecvInfo moon_bindgen_c_RecvInfo;"));
        assert!(stub.contains("value->from = from;"));
        assert!(!stub.contains("moon_bindgen_receive_packet"));
        assert!(!stub.contains("struct moon_bindgen_c_RecvInfo {"));
    }

    #[test]
    fn preserves_mutable_bindgen_struct_array_pointer_parameters() {
        let f = syn::parse_file(
            r#"
#[repr(C)]
pub struct curl_waitfd {
  pub fd: i32,
  pub events: i16,
  pub revents: i16,
}
unsafe extern "C" {
  pub fn curl_multi_poll(
    multi: *mut core::ffi::c_void,
    extra_fds: *mut curl_waitfd,
    extra_nfds: u32,
    timeout_ms: i32,
    numfds: *mut i32,
  ) -> u32;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );

        let moon = b.moonbit_source();
        assert!(moon.contains("pub fn CurlWaitfd::new("));
        assert!(moon.contains("extra_fds : @c.Pointer[CurlWaitfd], extra_nfds : UInt"));
        assert!(!moon.contains("extra_fds : CurlWaitfd"));
        assert!(!b.c_stub_source().contains("moon_bindgen_curl_multi_poll"));
    }

    #[test]
    fn preserves_rust_doc_comments_in_generated_moonbit() {
        let f = syn::parse_file(
            r#"
/// Number of packets.
pub type packet_count_t = u64;

/** Default packet count.
 *
 * Used when no limit is configured.
 */
pub const DEFAULT_PACKETS: packet_count_t = 4;

/// Information about a received packet.
#[repr(C)]
pub struct recv_info {
  /// Source address pointer.
  pub from: *mut u8,
  /// Source address length.
  pub from_len: u32,
}

unsafe extern "C" {
  /// Returns the library version.
  pub fn library_version() -> u32;

  /// Processes one received packet.
  ///
  /// Returns zero on success.
  pub fn receive_packet(info: *const recv_info) -> i32;
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_bindgen_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            false,
        );
        let moon = b.moonbit_source();

        assert!(moon.contains("/// Number of packets.\npub type PacketCountT = UInt64"));
        assert!(moon.contains(
            "/// Default packet count.\n///\n/// Used when no limit is configured.\npub const DEFAULT_PACKETS"
        ), "{moon}");
        assert!(
            moon.contains("/// Information about a received packet.\n#external\npub type RecvInfo")
        );
        assert!(moon.contains("/// Source address pointer.\npub fn RecvInfo::get_from"));
        assert!(
            moon.contains("/// Returns the library version.\npub extern \"c\" fn library_version")
        );
        assert!(moon.contains(
            "/// Processes one received packet.\n///\n/// Returns zero on success.\n#borrow(info)\npub extern \"c\" fn receive_packet"
        ));
    }
}
