use crate::model::{Bindings, Diagnostic, DiagnosticLevel, Model, Type};
use crate::{Ownership, Visibility};
use heck::ToSnakeCase;
use std::collections::BTreeSet;

#[allow(clippy::too_many_arguments)]
pub(crate) fn render(
    model: &Model,
    header: &str,
    footer: &str,
    visibility: Visibility,
    function_filter: fn(String) -> bool,
    type_filter: fn(String) -> bool,
    constant_filter: fn(String) -> bool,
    ownership_resolver: &dyn Fn(&str, &str) -> Ownership,
    function_rename: fn(String) -> String,
    type_rename: fn(String) -> String,
    constant_rename: fn(String) -> String,
) -> Bindings {
    let mut out = String::from("// Generated by moon-bindgen. Do not edit.\n");
    let mut diagnostics = model.diagnostics.clone();
    let stub = crate::stub::render(
        model,
        visibility,
        function_filter,
        type_filter,
        ownership_resolver,
        function_rename,
        type_rename,
    );
    diagnostics.extend(stub.diagnostics.iter().cloned());
    if !header.is_empty() {
        out.push_str(header);
        if !header.ends_with('\n') {
            out.push('\n');
        }
    }
    out.push('\n');
    out.push_str(&stub.moonbit_types);
    for (name, ty) in &model.aliases {
        if contains_nullable_callback(ty) {
            diagnostics.push(warning(
                name,
                "nullable callback is emitted as FuncRef; use a C adapter if null is possible",
            ));
        }
    }
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        if f.params
            .iter()
            .any(|(_, ty)| contains_nullable_callback(ty))
            || contains_nullable_callback(&f.result)
        {
            diagnostics.push(warning(
                &f.rust_name,
                "nullable callback is emitted as FuncRef; use a C adapter if null is possible",
            ));
        }
    }
    let mut opaque = BTreeSet::new();
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        for (_, t) in &f.params {
            collect_opaque(t, model, &mut opaque);
        }
        collect_opaque(&f.result, model, &mut opaque);
    }
    for name in &stub.value_structs {
        for field in &model.structs[name].fields {
            collect_opaque(&field.ty, model, &mut opaque);
        }
    }
    for name in opaque {
        if type_filter(name.clone())
            && !model.aliases.contains_key(&name)
            && !model.structs.contains_key(&name)
        {
            emit_external_type(&mut out, &name, "opaque C type", visibility, type_rename);
        }
    }
    for s in model.structs.values() {
        if !type_filter(s.name.clone()) || stub.value_structs.contains(&s.name) {
            continue;
        }
        emit_external_type(
            &mut out,
            &s.name,
            if s.is_union {
                "C union"
            } else {
                "#[repr(C)] struct"
            },
            visibility,
            type_rename,
        );
    }
    for (name, alias) in &model.aliases {
        if !type_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_type(alias, type_rename) {
            out.push_str(&format!(
                "///|\n{}type {} = {}\n\n",
                visibility.prefix(),
                renamed_type_ident(name, type_rename),
                ty
            ));
        }
    }
    for (name, c) in &model.constants {
        if !constant_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_type(&c.ty, type_rename) {
            out.push_str(&format!(
                "///|\n{}const {} : {} = {}\n\n",
                visibility.prefix(),
                renamed_constant_ident(name, constant_rename),
                ty,
                c.value
            ));
        }
    }
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        if stub.wrapped_symbols.contains(&f.symbol) {
            continue;
        }
        if contains_pointer_to_value_struct(&f.result, &stub.value_structs)
            || f.params
                .iter()
                .any(|(_, ty)| contains_pointer_to_value_struct(ty, &stub.value_structs))
        {
            diagnostics.push(warning(
                &f.rust_name,
                "pointer to a struct that is also used by value cannot share the generated value representation",
            ));
            continue;
        }
        if !f.params.iter().all(|(_, ty)| is_direct_ffi_type(ty, model))
            || !is_direct_ffi_type(&f.result, model)
        {
            diagnostics.push(warning(
                &f.rust_name,
                "signature cannot be represented safely by direct MoonBit FFI",
            ));
            continue;
        }
        if f.variadic {
            diagnostics.push(warning(
                &f.rust_name,
                "variadic functions cannot be represented in MoonBit FFI",
            ));
            continue;
        }
        let params: Option<Vec<_>> = f
            .params
            .iter()
            .map(|(n, t)| moon_type(t, type_rename).map(|ty| (n, ty, needs_ownership(t))))
            .collect();
        let (Some(params), Some(result)) = (params, moon_type(&f.result, type_rename)) else {
            diagnostics.push(warning(
                &f.rust_name,
                "signature contains an unsupported type",
            ));
            continue;
        };
        let ownerships = params
            .iter()
            .filter(|(_, _, needs_ownership)| *needs_ownership)
            .map(|(name, _, _)| {
                (
                    safe_value_ident(name),
                    ownership_resolver(&f.rust_name, name),
                )
            })
            .collect::<Vec<_>>();
        let borrowed = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Borrowed)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !borrowed.is_empty() {
            out.push_str(&format!("#borrow({})\n", borrowed.join(", ")));
        }
        let owned = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Owned)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !owned.is_empty() {
            out.push_str(&format!("#owned({})\n", owned.join(", ")));
        }
        out.push_str(&format!(
            "{}extern \"c\" fn {}(",
            visibility.prefix(),
            renamed_value_ident(&f.rust_name, function_rename)
        ));
        for (i, (name, ty, _)) in params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{} : {}", safe_value_ident(name), ty));
        }
        out.push(')');
        if result != "Unit" {
            out.push_str(&format!(" -> {result}"));
        }
        out.push_str(&format!(" = \"{}\"\n\n", f.symbol));
    }
    out.push_str(&stub.moonbit_functions);
    if !footer.is_empty() {
        if !out.ends_with("\n\n") {
            out.push('\n');
        }
        out.push_str(footer);
    }
    let trimmed_len = out.trim_end().len();
    out.truncate(trimmed_len);
    out.push('\n');
    Bindings::new(out, stub.c_source, diagnostics)
}
fn emit_external_type(
    out: &mut String,
    name: &str,
    note: &str,
    visibility: Visibility,
    type_rename: fn(String) -> String,
) {
    out.push_str(&format!(
        "///|\n#external\n{}type {} // {}\n\n",
        visibility.prefix(),
        renamed_type_ident(name, type_rename),
        note
    ));
}
fn moon_type(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    match ty {
        Type::Unit => Some("Unit".into()),
        Type::Path(p) => Some(match p.rsplit("::").next()? {
            "i8" | "u8" | "c_char" | "c_schar" | "c_uchar" => "Byte".into(),
            "i16" | "u16" | "c_short" | "c_ushort" | "i32" | "c_int" => "Int".into(),
            "u32" | "c_uint" => "UInt".into(),
            "i64" | "c_longlong" | "isize" | "c_long" => "Int64".into(),
            "u64" | "c_ulonglong" | "usize" | "c_ulong" | "size_t" => "UInt64".into(),
            "f32" | "c_float" => "Float".into(),
            "f64" | "c_double" => "Double".into(),
            "bool" => "Bool".into(),
            "c_void" => "Unit".into(),
            other => renamed_type_ident(other, type_rename),
        }),
        Type::Pointer { inner, mutable } => {
            // Both const and mutable scalar pointers use Ref at the MoonBit ABI
            // boundary. Retain mutability in the model for future ownership and
            // direction diagnostics.
            let _ = mutable;
            match inner.as_ref() {
                Type::Path(p) if matches!(p.rsplit("::").next(), Some("c_char" | "i8" | "u8")) => {
                    Some("Bytes".into())
                }
                Type::Path(p) if p.ends_with("c_void") => Some("RawPtr".into()),
                Type::Path(p) if primitive_moon_type(p).is_some() => {
                    Some(format!("Ref[{}]", primitive_moon_type(p)?))
                }
                Type::Path(p) => Some(renamed_type_ident(p.rsplit("::").next()?, type_rename)),
                _ => moon_type(inner, type_rename).map(|ty| format!("Ref[{ty}]")),
            }
        }
        Type::Array { inner, .. } => {
            moon_type(inner, type_rename).map(|t| format!("FixedArray[{t}]"))
        }
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            if *variadic {
                return None;
            }
            let params = params
                .iter()
                .map(|ty| moon_type(ty, type_rename))
                .collect::<Option<Vec<_>>>()?
                .join(", ");
            Some(format!(
                "FuncRef[({params}) -> {}]",
                moon_type(result, type_rename)?
            ))
        }
        Type::Unsupported => None,
    }
}
fn needs_ownership(t: &Type) -> bool {
    matches!(t, Type::Pointer { .. } | Type::Array { .. })
}

fn is_direct_ffi_type(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Unit => true,
        Type::Path(path) => {
            let name = path.rsplit("::").next().unwrap_or(path);
            if primitive_moon_type(path).is_some() || name == "c_void" {
                return true;
            }
            if model.structs.contains_key(name) {
                return false;
            }
            model
                .aliases
                .get(name)
                .is_some_and(|alias| is_direct_ffi_type(alias, model))
        }
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::Array { .. } => false,
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unsupported => false,
    }
}

fn is_pointer_pointee(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Path(_) => true,
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unit | Type::Array { .. } | Type::Unsupported => false,
    }
}
fn contains_nullable_callback(t: &Type) -> bool {
    match t {
        Type::FunctionPointer { nullable, .. } => *nullable,
        Type::Pointer { inner, .. } | Type::Array { inner, .. } => {
            contains_nullable_callback(inner)
        }
        _ => false,
    }
}
fn collect_opaque(t: &Type, model: &Model, out: &mut BTreeSet<String>) {
    match t {
        Type::Pointer { inner, .. } => {
            if let Type::Path(p) = inner.as_ref() {
                let n = p.rsplit("::").next().unwrap();
                if n == "c_void" {
                    out.insert("RawPtr".into());
                } else if !is_primitive(n)
                    && !model.structs.contains_key(n)
                    && !model.aliases.contains_key(n)
                {
                    out.insert(n.into());
                }
            } else {
                collect_opaque(inner, model, out);
            }
        }
        Type::Array { inner, .. } => collect_opaque(inner, model, out),
        Type::FunctionPointer { params, result, .. } => {
            for param in params {
                collect_opaque(param, model, out);
            }
            collect_opaque(result, model, out);
        }
        _ => {}
    }
}
fn contains_pointer_to_value_struct(t: &Type, value_structs: &BTreeSet<String>) -> bool {
    match t {
        Type::Pointer { inner, .. } => match inner.as_ref() {
            Type::Path(path) => value_structs.contains(path.rsplit("::").next().unwrap_or(path)),
            other => contains_pointer_to_value_struct(other, value_structs),
        },
        Type::Array { inner, .. } => contains_pointer_to_value_struct(inner, value_structs),
        Type::FunctionPointer { params, result, .. } => {
            params
                .iter()
                .any(|param| contains_pointer_to_value_struct(param, value_structs))
                || contains_pointer_to_value_struct(result, value_structs)
        }
        _ => false,
    }
}
fn is_primitive(s: &str) -> bool {
    matches!(
        s,
        "i8" | "u8"
            | "i16"
            | "u16"
            | "i32"
            | "u32"
            | "i64"
            | "u64"
            | "isize"
            | "usize"
            | "f32"
            | "f64"
            | "bool"
            | "c_char"
            | "c_schar"
            | "c_uchar"
            | "c_short"
            | "c_ushort"
            | "c_int"
            | "c_uint"
            | "c_long"
            | "c_ulong"
            | "c_longlong"
            | "c_ulonglong"
            | "c_float"
            | "c_double"
            | "c_void"
    )
}

fn primitive_moon_type(path: &str) -> Option<&'static str> {
    match path.rsplit("::").next()? {
        "i8" | "u8" | "c_char" | "c_schar" | "c_uchar" => Some("Byte"),
        "i16" | "u16" | "c_short" | "c_ushort" | "i32" | "c_int" => Some("Int"),
        "u32" | "c_uint" => Some("UInt"),
        "i64" | "c_longlong" | "isize" | "c_long" => Some("Int64"),
        "u64" | "c_ulonglong" | "usize" | "c_ulong" | "size_t" => Some("UInt64"),
        "f32" | "c_float" => Some("Float"),
        "f64" | "c_double" => Some("Double"),
        "bool" => Some("Bool"),
        _ => None,
    }
}
fn warning(item: &str, message: &str) -> Diagnostic {
    Diagnostic {
        level: DiagnosticLevel::Warning,
        item: item.into(),
        message: message.into(),
    }
}
fn safe_ident(s: &str) -> String {
    let s = s.replace("r#", "");
    if matches!(
        s.as_str(),
        "type"
            | "fn"
            | "let"
            | "const"
            | "struct"
            | "enum"
            | "match"
            | "if"
            | "else"
            | "loop"
            | "for"
            | "while"
            | "return"
            | "extern"
            | "pub"
            | "priv"
            | "true"
            | "false"
    ) {
        format!("{s}_")
    } else {
        s
    }
}

fn safe_value_ident(s: &str) -> String {
    let raw = s.replace("r#", "").to_snake_case();
    if raw.is_empty() {
        return "value".into();
    }
    safe_ident(&raw)
}

fn renamed_value_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_type_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_constant_ident(s: &str, rename: fn(String) -> String) -> String {
    let name = rename(s.to_owned());
    if name.is_empty() {
        "CONSTANT".into()
    } else {
        safe_ident(&name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{model::Model, parse};
    use heck::{ToShoutySnakeCase, ToUpperCamelCase};
    fn default_function_rename(name: String) -> String {
        name.to_snake_case()
    }
    fn default_type_rename(name: String) -> String {
        name.to_upper_camel_case()
    }
    fn default_constant_rename(name: String) -> String {
        name.to_shouty_snake_case()
    }
    #[test]
    fn generates_ffi() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Point { pub x:i32,pub y:i32 }
pub const ANSWER:u32=42;
unsafe extern "C" { pub fn c_move(p:*mut Point,n:usize)->i32; }
#[unsafe(no_mangle)] pub extern "C" fn rust_ping(value:u64)->bool { true }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "// custom footer",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("#external\ntype Point"));
        assert!(b.moonbit_source().contains("#borrow(p)"));
        assert!(
            b.moonbit_source()
                .contains("fn c_move(p : Point, n : UInt64) -> Int")
        );
        assert!(
            b.moonbit_source()
                .contains("fn rust_ping(value : UInt64) -> Bool")
        );
        assert!(b.moonbit_source().ends_with("// custom footer\n"));
    }

    #[test]
    fn generates_function_pointer_aliases_and_direct_callbacks() {
        let f = syn::parse_file(
            r#"
pub type Compare = ::std::option::Option<unsafe extern "C" fn(a: i32, b: i32) -> i32>;
unsafe extern "C" {
  pub fn sort_items(compare: Compare);
  pub fn get_callback() -> unsafe extern "C" fn(value: u64);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(
            b.moonbit_source()
                .contains("type Compare = FuncRef[(Int, Int) -> Int]")
        );
        assert!(
            b.moonbit_source()
                .contains("fn sort_items(compare : Compare)")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_callback() -> FuncRef[(UInt64) -> Unit]")
        );
        assert!(
            b.diagnostics()
                .iter()
                .any(|d| d.message.contains("nullable callback"))
        );
    }

    #[test]
    fn normalizes_c_function_names_and_groups_borrows() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_copy(src: *const i8, dst: *mut i8) -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("#borrow(src, dst)"));
        assert!(b.moonbit_source().contains("fn lz4_copy("));
        assert!(b.moonbit_source().contains("= \"LZ4_copy\""));
    }

    #[test]
    fn emits_public_types_and_functions_when_configured() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Context { _private: [u8; 0] }
pub type Count = u32;
pub const DEFAULT_COUNT: Count = 3;
unsafe extern "C" { pub fn library_count(context: *mut Context) -> Count; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("#external\npub type Context"));
        assert!(b.moonbit_source().contains("pub type Count = UInt"));
        assert!(
            b.moonbit_source()
                .contains("pub const DEFAULT_COUNT : Count = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("pub extern \"c\" fn library_count")
        );
    }

    #[test]
    fn filters_methods_using_original_rust_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_keep() -> i32;
                pub fn XXH_drop() -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |name| name.starts_with("LZ4_"),
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("fn lz4_keep"));
        assert!(!b.moonbit_source().contains("xxh_drop"));
        assert!(!b.moonbit_source().contains("XXH_drop"));
    }

    #[test]
    fn filters_types_and_constants_by_original_rust_names() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct KeepType { value: i32 }
#[repr(C)] pub struct DropType { value: i32 }
pub type KeepAlias = u32;
pub type DropAlias = u32;
pub const KEEP_CONST: u32 = 1;
pub const DROP_CONST: u32 = 2;
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |name| name.starts_with("Keep"),
            |name| name.starts_with("KEEP"),
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("type KeepType"));
        assert!(b.moonbit_source().contains("type KeepAlias"));
        assert!(!b.moonbit_source().contains("DropType"));
        assert!(!b.moonbit_source().contains("DropAlias"));
        assert!(b.moonbit_source().contains("const KEEP_CONST"));
        assert!(!b.moonbit_source().contains("DROP_CONST"));
    }

    #[test]
    fn normalizes_lowercase_types_and_scalar_pointers() {
        let f = syn::parse_file(
            r#"
pub type int_fast16_t = i16;
pub type stream_t = stream_u;
#[repr(C)] pub union stream_u { value: i32 }
unsafe extern "C" {
  pub fn update(value: *mut ::std::os::raw::c_int, stream: *mut stream_t);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("type IntFast16T = Int"));
        assert!(b.moonbit_source().contains("type StreamT = StreamU"));
        assert_eq!(b.moonbit_source().matches("type StreamT").count(), 1);
        assert!(
            b.moonbit_source()
                .contains("fn update(value : Ref[Int], stream : StreamT)")
        );
        assert!(!b.moonbit_source().contains("type c_int"));
    }

    #[test]
    fn resolves_parameter_ownership_with_original_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn register_data(kept: *mut u8, temporary: *const u8, raw: *mut u8);
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|function, parameter| match (function, parameter) {
                ("register_data", "kept") => Ownership::Owned,
                _ => Ownership::Borrowed,
            },
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("#owned(kept)"));
        assert!(b.moonbit_source().contains("#borrow(temporary, raw)"));
        assert!(!b.moonbit_source().contains("#owned(raw)"));
    }

    #[test]
    fn generates_struct_value_stubs_and_skips_remaining_unsupported_signatures() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Value { field: i32 }
unsafe extern "C" {
  pub fn by_value(value: Value) -> Value;
  pub fn double_pointer(value: *mut *mut i32);
  pub fn triple_pointer(value: *mut *mut *mut Context);
  pub fn raw_double_pointer(value: *mut *mut ::std::ffi::c_void);
  pub fn byte_double_pointer(value: *mut *mut u8);
  pub fn nullable(value: Option<*mut Value>);
  pub fn supported(value: *mut Value);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("struct Value"));
        assert!(b.moonbit_source().contains("fn by_value"));
        assert!(b.c_stub_source().contains("moon_bindgen_by_value"));
        assert!(b.c_stub_source().contains("moonbit_make_bytes"));
        assert!(
            b.moonbit_source()
                .contains("fn double_pointer(value : Ref[Ref[Int]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn triple_pointer(value : Ref[Ref[Context]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn raw_double_pointer(value : Ref[RawPtr])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn byte_double_pointer(value : Ref[Bytes])")
        );
        assert!(b.moonbit_source().contains("#external\ntype RawPtr"));
        assert!(!b.moonbit_source().contains("fn nullable"));
        assert!(!b.moonbit_source().contains("fn supported"));
        assert_eq!(b.diagnostics().len(), 2);
    }

    #[test]
    fn generates_nested_struct_dependencies_and_fixed_array_marshalling() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Inner { value: i32, bytes: [u8; 4] }
#[repr(C)] pub struct Outer { inner: Inner, enabled: bool }
#[repr(C)] pub struct PointerHolder { value: *mut *mut i32 }
unsafe extern "C" {
  pub fn round_trip(value: Outer) -> Outer;
  pub fn consume_pointer_holder(value: PointerHolder);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
        );
        assert!(b.moonbit_source().contains("pub(all) struct Inner"));
        assert!(b.moonbit_source().contains("value : Ref[Ref[Int]]"));
        assert!(b.c_stub_source().contains("int32_t * * value_value"));
        assert!(b.moonbit_source().contains("pub(all) struct Outer"));
        assert!(
            b.moonbit_source()
                .contains("value.inner.bytes.length() != 4")
        );
        assert!(
            b.c_stub_source()
                .contains("memcpy(moon_bindgen_arg_value.inner.bytes")
        );
        assert!(
            b.c_stub_source()
                .contains("moonbit_make_bytes((int32_t)sizeof(result), 0)")
        );
    }

    #[test]
    fn renames_functions_types_constants_and_type_references() {
        let f = syn::parse_file(
            r#"
pub type LIB_count_t = u32;
pub const LIB_DEFAULT_COUNT: LIB_count_t = 3;
unsafe extern "C" { pub fn LIB_getCount() -> LIB_count_t; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let function_rename =
            |name: String| name.strip_prefix("LIB_").unwrap_or(&name).to_snake_case();
        let type_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_upper_camel_case()
        };
        let constant_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_shouty_snake_case()
        };
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrowed,
            function_rename,
            type_rename,
            constant_rename,
        );
        assert!(b.moonbit_source().contains("type CountT = UInt"));
        assert!(
            b.moonbit_source()
                .contains("const DEFAULT_COUNT : CountT = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_count() -> CountT = \"LIB_getCount\"")
        );
    }
}
