use crate::model::{Bindings, Diagnostic, DiagnosticLevel, Model, Type};
use crate::{Nullability, NullabilityPosition, Ownership, Visibility};
use heck::ToSnakeCase;
use std::collections::{BTreeMap, BTreeSet};

#[allow(clippy::too_many_arguments)]
pub(crate) fn render(
    model: &Model,
    header: &str,
    footer: &str,
    visibility: Visibility,
    function_filter: fn(String) -> bool,
    type_filter: fn(String) -> bool,
    constant_filter: fn(String) -> bool,
    ownership_resolver: &dyn Fn(&str, &str) -> Ownership,
    nullability_resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    function_rename: fn(String) -> String,
    type_rename: fn(String) -> String,
    constant_rename: fn(String) -> String,
    use_bytes: bool,
    emit_pointer_types: bool,
) -> Bindings {
    let mut out = String::from("// Generated by moon-bindgen. Do not edit.\n");
    let mut diagnostics = model.diagnostics.clone();
    let mut stub = crate::stub::render(
        model,
        visibility,
        function_filter,
        type_filter,
        ownership_resolver,
        function_rename,
        type_rename,
        use_bytes,
    );
    diagnostics.extend(stub.diagnostics.iter().cloned());
    if !header.is_empty() {
        out.push_str(header);
        if !header.ends_with('\n') {
            out.push('\n');
        }
    }
    out.push('\n');
    out.push_str(&stub.moonbit_types);
    if emit_pointer_types {
        out.push_str(&format!(
            "///|\n#external\n{}type Ptr[T] // mutable C pointer\n\n///|\n#external\n{}type ConstPtr[T] // const C pointer\n\n",
            visibility.prefix(),
            visibility.prefix(),
        ));
    }
    let mut opaque = BTreeSet::new();
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        for (_, t) in &f.params {
            collect_opaque(t, model, &mut opaque);
        }
        collect_opaque(&f.result, model, &mut opaque);
    }
    for name in &stub.value_structs {
        for field in &model.structs[name].fields {
            collect_opaque(&field.ty, model, &mut opaque);
        }
    }
    let mut nullable_externals = BTreeSet::new();
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        for (name, ty) in &f.params {
            if effective_nullability(
                nullability_resolver,
                &f.rust_name,
                NullabilityPosition::Parameter(name.clone()),
            ) == Nullability::Nullable
                && let Some(ty) = external_pointer_type(ty, type_rename)
            {
                nullable_externals.insert(ty);
            }
        }
        if effective_nullability(
            nullability_resolver,
            &f.rust_name,
            NullabilityPosition::Return,
        ) == Nullability::Nullable
            && let Some(ty) = external_pointer_type(&f.result, type_rename)
        {
            nullable_externals.insert(ty);
        }
    }
    let mut pointer_carriers = BTreeMap::new();
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        for (_, ty) in &f.params {
            collect_pointer_carriers(ty, type_rename, use_bytes, &mut pointer_carriers);
        }
        collect_pointer_carriers(&f.result, type_rename, use_bytes, &mut pointer_carriers);
    }
    for name in &stub.value_structs {
        for field in &model.structs[name].fields {
            collect_pointer_carriers(&field.ty, type_rename, use_bytes, &mut pointer_carriers);
        }
    }
    for name in opaque {
        if type_filter(name.clone())
            && !model.aliases.contains_key(&name)
            && !model.structs.contains_key(&name)
        {
            emit_external_type(&mut out, &name, "opaque C type", visibility, type_rename);
        }
    }
    for s in model.structs.values() {
        if !type_filter(s.name.clone()) || stub.value_structs.contains(&s.name) {
            continue;
        }
        emit_external_type(
            &mut out,
            &s.name,
            if s.is_union {
                "C union"
            } else {
                "#[repr(C)] struct"
            },
            visibility,
            type_rename,
        );
    }
    emit_pointer_carriers(&mut out, &mut stub.c_source, &pointer_carriers, visibility);
    let pointer_slots = collect_pointer_slots(model, function_filter, type_rename);
    emit_pointer_slots(&mut out, &mut stub.c_source, &pointer_slots);
    emit_nullable_external_helpers(
        &mut out,
        &mut stub.c_source,
        &nullable_externals,
        visibility,
    );
    for (name, alias) in &model.aliases {
        if !type_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_alias_type(name, alias, model, type_filter, type_rename) {
            out.push_str(&format!(
                "///|\n{}type {} = {}\n\n",
                visibility.prefix(),
                renamed_type_ident(name, type_rename),
                ty
            ));
        }
    }
    for (name, c) in &model.constants {
        if !constant_filter(name.clone()) {
            continue;
        }
        if let Some(ty) = moon_type(&c.ty, type_rename) {
            out.push_str(&format!(
                "///|\n{}const {} : {} = {}\n\n",
                visibility.prefix(),
                renamed_constant_ident(name, constant_rename),
                ty,
                c.value
            ));
        }
    }
    for f in model.functions.values() {
        if !function_filter(f.rust_name.clone()) {
            continue;
        }
        if stub.wrapped_symbols.contains(&f.symbol) {
            continue;
        }
        if contains_pointer_to_value_struct(&f.result, &stub.value_structs)
            || f.params
                .iter()
                .any(|(_, ty)| contains_pointer_to_value_struct(ty, &stub.value_structs))
        {
            diagnostics.push(warning(
                &f.rust_name,
                "pointer to a struct that is also used by value cannot share the generated value representation",
            ));
            continue;
        }
        if !f.params.iter().all(|(_, ty)| is_direct_ffi_type(ty, model))
            || !is_direct_ffi_type(&f.result, model)
        {
            diagnostics.push(warning(
                &f.rust_name,
                "signature cannot be represented safely by direct MoonBit FFI",
            ));
            continue;
        }
        if f.variadic {
            diagnostics.push(warning(
                &f.rust_name,
                "variadic functions cannot be represented in MoonBit FFI",
            ));
            continue;
        }
        if f.params
            .iter()
            .any(|(_, ty)| pointer_slot_spec(ty, model, type_rename).is_some())
        {
            emit_pointer_slot_function(
                &mut out,
                &mut stub.c_source,
                f,
                model,
                visibility,
                ownership_resolver,
                function_rename,
                type_rename,
                use_bytes,
            );
            continue;
        }
        if function_needs_nullable_wrapper(f, nullability_resolver, type_rename) {
            emit_nullable_function(
                &mut out,
                f,
                model,
                visibility,
                ownership_resolver,
                nullability_resolver,
                function_rename,
                type_rename,
                use_bytes,
            );
            continue;
        }
        let params: Option<Vec<_>> = f
            .params
            .iter()
            .map(|(n, t)| {
                moon_parameter_type(
                    t,
                    model,
                    &f.rust_name,
                    n,
                    nullability_resolver,
                    type_rename,
                    use_bytes,
                )
                .map(|ty| (n, ty, needs_ownership_resolved(t, model)))
            })
            .collect();
        let result = moon_result_type(
            &f.result,
            model,
            &f.rust_name,
            nullability_resolver,
            type_rename,
            use_bytes,
        );
        let (Some(params), Some(result)) = (params, result) else {
            diagnostics.push(warning(
                &f.rust_name,
                "signature contains an unsupported type",
            ));
            continue;
        };
        let ownerships = params
            .iter()
            .filter(|(_, _, needs_ownership)| *needs_ownership)
            .map(|(name, _, _)| {
                (
                    safe_value_ident(name),
                    ownership_resolver(&f.rust_name, name),
                )
            })
            .collect::<Vec<_>>();
        let borrowed = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Borrow)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !borrowed.is_empty() {
            out.push_str(&format!("#borrow({})\n", borrowed.join(", ")));
        }
        let owned = ownerships
            .iter()
            .filter(|(_, ownership)| *ownership == Ownership::Owned)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !owned.is_empty() {
            out.push_str(&format!("#owned({})\n", owned.join(", ")));
        }
        out.push_str(&format!(
            "{}extern \"c\" fn {}(",
            visibility.prefix(),
            renamed_value_ident(&f.rust_name, function_rename)
        ));
        for (i, (name, ty, _)) in params.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{} : {}", safe_value_ident(name), ty));
        }
        out.push(')');
        if result != "Unit" {
            out.push_str(&format!(" -> {result}"));
        }
        out.push_str(&format!(" = \"{}\"\n\n", f.symbol));
    }
    out.push_str(&stub.moonbit_functions);
    if !footer.is_empty() {
        if !out.ends_with("\n\n") {
            out.push('\n');
        }
        out.push_str(footer);
    }
    let trimmed_len = out.trim_end().len();
    out.truncate(trimmed_len);
    out.push('\n');
    Bindings::new(out, stub.c_source, diagnostics)
}

fn moon_alias_type(
    name: &str,
    alias: &Type,
    model: &Model,
    type_filter: fn(String) -> bool,
    type_rename: fn(String) -> String,
) -> Option<String> {
    let emitted_name = renamed_type_ident(name, type_rename);
    let mut current = alias;
    let mut seen = BTreeSet::new();
    loop {
        let ty = moon_type(current, type_rename)?;
        let Type::Path(path) = current else {
            return (ty != emitted_name).then_some(ty);
        };
        let target = path.rsplit("::").next()?;
        let should_resolve = ty == emitted_name
            || (!type_filter(target.to_owned()) && model.aliases.contains_key(target));
        if !should_resolve {
            return Some(ty);
        }
        if !seen.insert(target) {
            return None;
        }
        current = model.aliases.get(target)?;
    }
}

fn effective_nullability(
    resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    function: &str,
    position: NullabilityPosition,
) -> Nullability {
    match resolver(function, position.clone()) {
        Nullability::Unspecified => match position {
            NullabilityPosition::Return => Nullability::Nullable,
            NullabilityPosition::Parameter(_) => Nullability::NonNull,
        },
        value => value,
    }
}

fn external_pointer_type(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    let mut current = ty;
    let mut depth = 0;
    while let Type::Pointer { inner, .. } = current {
        depth += 1;
        current = inner;
    }
    let Type::Path(path) = current else {
        return None;
    };
    let base = path.rsplit("::").next()?;
    if depth == 0 || (is_primitive(base) && base != "c_void") {
        return None;
    }
    if depth >= 2 {
        raw_pointer_carrier_name(ty, type_rename)
    } else {
        moon_type(ty, type_rename)
    }
}

fn function_needs_nullable_wrapper(
    function: &crate::model::Function,
    resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    type_rename: fn(String) -> String,
) -> bool {
    function.params.iter().any(|(name, ty)| {
        external_pointer_type(ty, type_rename).is_some()
            && effective_nullability(
                resolver,
                &function.rust_name,
                NullabilityPosition::Parameter(name.clone()),
            ) == Nullability::Nullable
    }) || (external_pointer_type(&function.result, type_rename).is_some()
        && effective_nullability(resolver, &function.rust_name, NullabilityPosition::Return)
            == Nullability::Nullable)
}

fn ensure_c_stub_prelude(c: &mut String) {
    if c.is_empty() {
        c.push_str("// Generated by moon-bindgen. Do not edit.\n#include <moonbit.h>\n#include <stdint.h>\n#include <string.h>\n\n");
    } else if !c.ends_with('\n') {
        c.push('\n');
    }
}

fn emit_nullable_external_helpers(
    moon: &mut String,
    c: &mut String,
    types: &BTreeSet<String>,
    visibility: Visibility,
) {
    if types.is_empty() {
        return;
    }
    ensure_c_stub_prelude(c);
    for ty in types {
        let prefix = format!("moon_bindgen_{}", ty.to_snake_case());
        let null_symbol = format!("{prefix}_null");
        let is_null_symbol = format!("{prefix}_is_null");
        moon.push_str(&format!(
            "///|\nextern \"c\" fn {null_symbol}() -> {ty} = \"{null_symbol}\"\n\n"
        ));
        moon.push_str(&format!(
            "///|\n#borrow(value)\nextern \"c\" fn {is_null_symbol}(value : {ty}) -> Bool = \"{is_null_symbol}\"\n\n"
        ));
        moon.push_str(&format!(
            "///|\n{}fn {ty}::null() -> {ty} {{\n  {null_symbol}()\n}}\n\n",
            visibility.prefix()
        ));
        moon.push_str(&format!(
            "///|\n{}fn {ty}::is_null(self : {ty}) -> Bool {{\n  {is_null_symbol}(self)\n}}\n\n",
            visibility.prefix()
        ));
        c.push_str(&format!(
            "MOONBIT_FFI_EXPORT\nvoid *{null_symbol}(void) {{\n  return (void *)0;\n}}\n\n"
        ));
        c.push_str(&format!(
            "MOONBIT_FFI_EXPORT\nint32_t {is_null_symbol}(void *value) {{\n  return value == (void *)0;\n}}\n\n"
        ));
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_nullable_function(
    out: &mut String,
    function: &crate::model::Function,
    model: &Model,
    visibility: Visibility,
    ownership_resolver: &dyn Fn(&str, &str) -> Ownership,
    nullability_resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    function_rename: fn(String) -> String,
    type_rename: fn(String) -> String,
    use_bytes: bool,
) {
    let params = function
        .params
        .iter()
        .map(|(name, ty)| {
            let raw_ty = moon_parameter_type(
                ty,
                model,
                &function.rust_name,
                name,
                nullability_resolver,
                type_rename,
                use_bytes,
            )
            .expect("validated direct FFI type");
            let nullable = external_pointer_type(ty, type_rename).is_some()
                && effective_nullability(
                    nullability_resolver,
                    &function.rust_name,
                    NullabilityPosition::Parameter(name.clone()),
                ) == Nullability::Nullable;
            (name, ty, raw_ty, nullable)
        })
        .collect::<Vec<_>>();
    let raw_result = moon_result_type(
        &function.result,
        model,
        &function.rust_name,
        nullability_resolver,
        type_rename,
        use_bytes,
    )
    .expect("validated direct FFI type");
    let nullable_result = external_pointer_type(&function.result, type_rename).is_some()
        && effective_nullability(
            nullability_resolver,
            &function.rust_name,
            NullabilityPosition::Return,
        ) == Nullability::Nullable;
    let raw_name = format!(
        "moon_bindgen_{}_raw",
        renamed_value_ident(&function.rust_name, function_rename)
    );

    let ownerships = params
        .iter()
        .filter(|(_, ty, _, _)| needs_ownership(ty))
        .map(|(name, _, _, _)| {
            (
                safe_value_ident(name),
                ownership_resolver(&function.rust_name, name),
            )
        })
        .collect::<Vec<_>>();
    for (annotation, ownership) in [("borrow", Ownership::Borrow), ("owned", Ownership::Owned)] {
        let names = ownerships
            .iter()
            .filter(|(_, value)| *value == ownership)
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>();
        if !names.is_empty() {
            out.push_str(&format!("#{annotation}({})\n", names.join(", ")));
        }
    }
    out.push_str(&format!("extern \"c\" fn {raw_name}("));
    for (index, (name, _, raw_ty, _)) in params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{} : {raw_ty}", safe_value_ident(name)));
    }
    out.push(')');
    if raw_result != "Unit" {
        out.push_str(&format!(" -> {raw_result}"));
    }
    out.push_str(&format!(" = \"{}\"\n\n", function.symbol));

    let public_name = renamed_value_ident(&function.rust_name, function_rename);
    out.push_str(&format!("///|\n{}fn {public_name}(", visibility.prefix()));
    for (index, (name, _, raw_ty, nullable)) in params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        let suffix = if *nullable { "?" } else { "" };
        out.push_str(&format!("{} : {raw_ty}{suffix}", safe_value_ident(name)));
    }
    out.push(')');
    if raw_result != "Unit" {
        let suffix = if nullable_result { "?" } else { "" };
        out.push_str(&format!(" -> {raw_result}{suffix}"));
    }
    out.push_str(" {\n");
    for (name, _, raw_ty, nullable) in &params {
        if *nullable {
            let name = safe_value_ident(name);
            out.push_str(&format!(
                "  let {name}_raw = match {name} {{\n    Some(value) => value\n    None => {raw_ty}::null()\n  }}\n"
            ));
        }
    }
    let args = params
        .iter()
        .map(|(name, _, _, nullable)| {
            let name = safe_value_ident(name);
            if *nullable {
                format!("{name}_raw")
            } else {
                name
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    if nullable_result {
        out.push_str(&format!("  let result = {raw_name}({args})\n"));
        out.push_str("  if result.is_null() {\n    None\n  } else {\n    Some(result)\n  }\n");
    } else {
        out.push_str(&format!("  {raw_name}({args})\n"));
    }
    out.push_str("}\n\n");
}

fn emit_external_type(
    out: &mut String,
    name: &str,
    note: &str,
    visibility: Visibility,
    type_rename: fn(String) -> String,
) {
    out.push_str(&format!(
        "///|\n#external\n{}type {} // {}\n\n",
        visibility.prefix(),
        renamed_type_ident(name, type_rename),
        note
    ));
}

#[derive(Clone)]
struct PointerSlotSpec {
    name: String,
    moon_value: String,
    c_value: String,
    value_is_pointer: bool,
}

fn pointer_slot_spec(
    ty: &Type,
    model: &Model,
    type_rename: fn(String) -> String,
) -> Option<PointerSlotSpec> {
    let Type::Pointer { inner, .. } = ty else {
        return None;
    };
    match inner.as_ref() {
        Type::Pointer { .. } => {
            let moon_value = raw_pointer_carrier_name(inner, type_rename)?;
            Some(PointerSlotSpec {
                name: format!("Ptr[{moon_value}]"),
                moon_value,
                c_value: c_pointer_value_type(inner, model)?,
                value_is_pointer: true,
            })
        }
        Type::Path(path)
            if primitive_moon_type(path).is_some()
                && !matches!(path.rsplit("::").next(), Some("u8" | "i8" | "c_char")) =>
        {
            let moon_value = primitive_moon_type(path)?.to_owned();
            Some(PointerSlotSpec {
                name: format!("Ptr[{moon_value}]"),
                moon_value,
                c_value: crate::stub::c_type(inner, model)?,
                value_is_pointer: false,
            })
        }
        _ => None,
    }
}

fn c_pointer_value_type(ty: &Type, model: &Model) -> Option<String> {
    crate::stub::c_type(ty, model).or_else(|| match ty {
        Type::Path(_) => Some("void".into()),
        Type::Pointer { inner, mutable } => Some(format!(
            "{}{} *",
            if *mutable { "" } else { "const " },
            c_pointer_value_type(inner, model)?
        )),
        _ => None,
    })
}

fn c_pointer_decl(ty: &Type, name: &str, model: &Model) -> Option<String> {
    crate::stub::c_decl(ty, name, model)
        .or_else(|| c_pointer_value_type(ty, model).map(|ty| format!("{ty} {name}")))
}

fn collect_pointer_slots(
    model: &Model,
    function_filter: fn(String) -> bool,
    type_rename: fn(String) -> String,
) -> BTreeMap<String, PointerSlotSpec> {
    let mut slots = BTreeMap::new();
    for function in model.functions.values() {
        if !function_filter(function.rust_name.clone()) {
            continue;
        }
        for (_, ty) in &function.params {
            if let Some(slot) = pointer_slot_spec(ty, model, type_rename) {
                slots.entry(slot.name.clone()).or_insert(slot);
            }
        }
    }
    slots
}

fn emit_pointer_slots(
    moon: &mut String,
    c: &mut String,
    slots: &BTreeMap<String, PointerSlotSpec>,
) {
    if slots.is_empty() {
        return;
    }
    ensure_c_stub_prelude(c);
    for slot in slots.values() {
        let prefix = format!("moon_bindgen_{}", pointer_symbol(&slot.name));
        let new = format!("{prefix}_new");
        let get = format!("{prefix}_get");
        if slot.value_is_pointer {
            moon.push_str("#borrow(initial)\n");
        }
        moon.push_str(&format!(
            "extern \"c\" fn {new}(initial : {}) -> {} = \"{new}\"\n\n",
            slot.moon_value, slot.name
        ));
        moon.push_str(&format!(
            "#borrow(slot)\nextern \"c\" fn {get}(slot : {}) -> {} = \"{get}\"\n\n",
            slot.name, slot.moon_value
        ));
        c.push_str(&format!(
            "typedef struct {{ {} value; }} {prefix}_t;\n\nMOONBIT_FFI_EXPORT\nvoid *{new}({} initial) {{\n  {prefix}_t *slot = ({prefix}_t *)moonbit_make_external_object(NULL, sizeof({prefix}_t));\n  slot->value = initial;\n  return slot;\n}}\n\nMOONBIT_FFI_EXPORT\n{} {get}(void *raw_slot) {{\n  return (({prefix}_t *)raw_slot)->value;\n}}\n\n",
            slot.c_value, slot.c_value, slot.c_value
        ));
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_pointer_slot_function(
    moon: &mut String,
    c: &mut String,
    function: &crate::model::Function,
    model: &Model,
    visibility: Visibility,
    ownership_resolver: &dyn Fn(&str, &str) -> Ownership,
    function_rename: fn(String) -> String,
    type_rename: fn(String) -> String,
    use_bytes: bool,
) {
    ensure_c_stub_prelude(c);
    let shim = format!(
        "moon_bindgen_{}_pointer_out",
        renamed_value_ident(&function.rust_name, function_rename)
    );
    let mut public_params = Vec::new();
    let mut raw_params = Vec::new();
    let mut raw_borrowed = Vec::new();
    let mut raw_owned = Vec::new();
    let mut setup = String::new();
    let mut raw_args = Vec::new();
    let mut updates = String::new();
    let mut c_params = Vec::new();
    let mut c_args = Vec::new();

    for (name, ty) in &function.params {
        let safe = safe_value_ident(name);
        let public_ty = moon_type_config(ty, type_rename, use_bytes).unwrap();
        public_params.push(format!("{safe} : {public_ty}"));
        if let Some(slot) = pointer_slot_spec(ty, model, type_rename) {
            let slot_var = format!("{safe}_slot");
            let prefix = format!("moon_bindgen_{}", pointer_symbol(&slot.name));
            setup.push_str(&format!("  let {slot_var} = {prefix}_new({safe}.val)\n"));
            updates.push_str(&format!("  {safe}.val = {prefix}_get({slot_var})\n"));
            raw_params.push(format!("{safe} : {}", slot.name));
            raw_borrowed.push(safe.clone());
            raw_args.push(slot_var);
            c_params.push(format!("void *{safe}"));
            c_args.push(format!(
                "&((moon_bindgen_{}_t *){safe})->value",
                pointer_symbol(&slot.name)
            ));
        } else {
            raw_params.push(format!("{safe} : {public_ty}"));
            if needs_ownership_resolved(ty, model) {
                match ownership_resolver(&function.rust_name, name) {
                    Ownership::Borrow => raw_borrowed.push(safe.clone()),
                    Ownership::Owned => raw_owned.push(safe.clone()),
                }
            }
            raw_args.push(safe.clone());
            c_params.push(format!(
                "{} {safe}",
                crate::stub::c_abi_type(ty, model).unwrap()
            ));
            c_args.push(crate::stub::c_call_expr(&safe, ty, model));
        }
    }
    if !raw_borrowed.is_empty() {
        moon.push_str(&format!("#borrow({})\n", raw_borrowed.join(", ")));
    }
    if !raw_owned.is_empty() {
        moon.push_str(&format!("#owned({})\n", raw_owned.join(", ")));
    }
    let result = moon_type_config(&function.result, type_rename, use_bytes).unwrap();
    moon.push_str(&format!(
        "extern \"c\" fn {shim}({}){} = \"{shim}\"\n\n",
        raw_params.join(", "),
        if result == "Unit" {
            String::new()
        } else {
            format!(" -> {result}")
        }
    ));
    let public_name = renamed_value_ident(&function.rust_name, function_rename);
    moon.push_str(&format!(
        "///|\n{}fn {public_name}({}) -> {result} {{\n{setup}",
        visibility.prefix(),
        public_params.join(", "),
    ));
    if result == "Unit" {
        moon.push_str(&format!("  {shim}({})\n{updates}", raw_args.join(", ")));
    } else {
        moon.push_str(&format!(
            "  let result = {shim}({})\n{updates}  result\n",
            raw_args.join(", ")
        ));
    }
    moon.push_str("}\n\n");

    c.push_str(&format!(
        "extern {} {}({});\nMOONBIT_FFI_EXPORT\n{} {shim}({}) {{\n",
        crate::stub::c_type(&function.result, model).unwrap(),
        function.symbol,
        function
            .params
            .iter()
            .map(|(name, ty)| c_pointer_decl(ty, name, model).unwrap())
            .collect::<Vec<_>>()
            .join(", "),
        crate::stub::c_abi_type(&function.result, model).unwrap(),
        c_params.join(", ")
    ));
    let call = format!("{}({})", function.symbol, c_args.join(", "));
    if result == "Unit" {
        c.push_str(&format!("  {call};\n}}\n\n"));
    } else {
        c.push_str(&format!("  return {call};\n}}\n\n"));
    }
}

fn emit_pointer_carriers(
    moon: &mut String,
    c: &mut String,
    carriers: &BTreeMap<String, String>,
    visibility: Visibility,
) {
    if carriers.is_empty() {
        return;
    }
    ensure_c_stub_prelude(c);
    for (name, target) in carriers {
        let prefix = format!("moon_bindgen_{}", pointer_symbol(name));
        let null = format!("{prefix}_null");
        let is_null = format!("{prefix}_is_null");
        moon.push_str(&format!(
            "///|\n{}extern \"c\" fn {null}() -> {name} = \"{null}\"\n\n///|\n#borrow(value)\n{}extern \"c\" fn {is_null}(value : {name}) -> Bool = \"{is_null}\"\n\n",
            visibility.prefix(), visibility.prefix()
        ));
        c.push_str(&format!(
            "MOONBIT_FFI_EXPORT\nvoid *{null}(void) {{ return NULL; }}\n\nMOONBIT_FFI_EXPORT\nint32_t {is_null}(void *value) {{ return value == NULL; }}\n\n"
        ));
        if matches!(name.as_str(), "Ptr[Byte]" | "ConstPtr[Byte]") {
            let copy = format!("{prefix}_copy_bytes");
            moon.push_str(&format!(
                "///|\n#borrow(pointer)\n{}extern \"c\" fn {copy}(pointer : {name}, length : UInt64) -> Bytes = \"{copy}\"\n\n",
                visibility.prefix()
            ));
            c.push_str(&format!(
                "MOONBIT_FFI_EXPORT\nmoonbit_bytes_t {copy}(const uint8_t *pointer, uint64_t length) {{\n  moonbit_bytes_t bytes = moonbit_make_bytes((int32_t)length, 0);\n  if (length != 0) memcpy(bytes, pointer, (size_t)length);\n  return bytes;\n}}\n\n"
            ));
        } else if primitive_c_type_for_pointer(target).is_some() {
            let read = format!("{prefix}_read");
            let c_ty = primitive_c_type_for_pointer(target).unwrap();
            moon.push_str(&format!(
                "///|\n#borrow(pointer)\n{}extern \"c\" fn {read}(pointer : {name}) -> {target} = \"{read}\"\n\n",
                visibility.prefix()
            ));
            c.push_str(&format!(
                "MOONBIT_FFI_EXPORT\n{c_ty} {read}(const {c_ty} *pointer) {{ return *pointer; }}\n\n"
            ));
        } else {
            let deref = format!("{prefix}_deref");
            moon.push_str(&format!(
                "///|\n#borrow(pointer)\n{}extern \"c\" fn {deref}(pointer : {name}) -> {target} = \"{deref}\"\n\n",
                visibility.prefix()
            ));
            c.push_str(&format!(
                "MOONBIT_FFI_EXPORT\nvoid *{deref}(void *pointer) {{ return {}; }}\n\n",
                if target.starts_with("Ptr[") || target.starts_with("ConstPtr[") {
                    "*(void **)pointer"
                } else {
                    "pointer"
                }
            ));
        }
    }
}

fn primitive_c_type_for_pointer(moon: &str) -> Option<&'static str> {
    match moon {
        "Byte" => Some("uint8_t"),
        "Int" => Some("int32_t"),
        "UInt" => Some("uint32_t"),
        "Int64" => Some("int64_t"),
        "UInt64" => Some("uint64_t"),
        "Float" => Some("float"),
        "Double" => Some("double"),
        "Bool" => Some("int32_t"),
        _ => None,
    }
}

fn collect_pointer_carriers(
    ty: &Type,
    type_rename: fn(String) -> String,
    use_bytes: bool,
    out: &mut BTreeMap<String, String>,
) {
    if pointer_depth(ty) >= 2 || (!use_bytes && is_direct_byte_pointer(ty)) {
        collect_raw_pointer_carrier(ty, type_rename, out);
    }
    if let Type::Pointer { inner, .. } = ty
        && matches!(inner.as_ref(), Type::Pointer { .. })
    {
        collect_raw_pointer_carrier(inner, type_rename, out);
    }
    match ty {
        Type::Pointer { inner, .. } | Type::Array { inner, .. } => {
            collect_pointer_carriers(inner, type_rename, use_bytes, out)
        }
        Type::FunctionPointer { params, result, .. } => {
            for param in params {
                collect_pointer_carriers(param, type_rename, use_bytes, out);
            }
            collect_pointer_carriers(result, type_rename, use_bytes, out);
        }
        _ => {}
    }
}

fn pointer_depth(ty: &Type) -> usize {
    match ty {
        Type::Pointer { inner, .. } => 1 + pointer_depth(inner),
        _ => 0,
    }
}

fn collect_raw_pointer_carrier(
    ty: &Type,
    type_rename: fn(String) -> String,
    out: &mut BTreeMap<String, String>,
) {
    let Some(name) = raw_pointer_carrier_name(ty, type_rename) else {
        return;
    };
    let Type::Pointer { inner, .. } = ty else {
        return;
    };
    let target = match inner.as_ref() {
        Type::Pointer { .. } => {
            collect_raw_pointer_carrier(inner, type_rename, out);
            raw_pointer_carrier_name(inner, type_rename).unwrap()
        }
        Type::Path(path) => primitive_moon_type(path)
            .map(str::to_owned)
            .unwrap_or_else(|| renamed_type_ident(path.rsplit("::").next().unwrap(), type_rename)),
        _ => return,
    };
    out.entry(name).or_insert(target);
}

fn raw_pointer_carrier_name(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    let Type::Pointer { inner, mutable } = ty else {
        return None;
    };
    let target = match inner.as_ref() {
        Type::Pointer { .. } => raw_pointer_carrier_name(inner, type_rename)?,
        Type::Path(path) => match path.rsplit("::").next()? {
            "c_void" => "Unit".into(),
            primitive => primitive_moon_type(primitive)
                .map(str::to_owned)
                .unwrap_or_else(|| renamed_type_ident(primitive, type_rename)),
        },
        _ => return None,
    };
    Some(format!(
        "{}[{target}]",
        if *mutable { "Ptr" } else { "ConstPtr" }
    ))
}

fn pointer_symbol(ty: &str) -> String {
    ty.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split('_')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("_")
}

fn moon_type(ty: &Type, type_rename: fn(String) -> String) -> Option<String> {
    moon_type_config(ty, type_rename, true)
}

fn moon_type_config(
    ty: &Type,
    type_rename: fn(String) -> String,
    use_bytes: bool,
) -> Option<String> {
    match ty {
        Type::Unit => Some("Unit".into()),
        Type::Path(p) => Some(match p.rsplit("::").next()? {
            "i8" | "u8" | "c_char" | "c_schar" | "c_uchar" => "Byte".into(),
            "i16" | "u16" | "c_short" | "c_ushort" | "i32" | "c_int" => "Int".into(),
            "u32" | "c_uint" => "UInt".into(),
            "i64" | "c_longlong" | "isize" | "c_long" => "Int64".into(),
            "u64" | "c_ulonglong" | "usize" | "c_ulong" | "size_t" => "UInt64".into(),
            "f32" | "c_float" => "Float".into(),
            "f64" | "c_double" => "Double".into(),
            "bool" => "Bool".into(),
            "c_void" => "Unit".into(),
            other => renamed_type_ident(other, type_rename),
        }),
        Type::Pointer { inner, mutable } => {
            // Both const and mutable scalar pointers use Ref at the MoonBit ABI
            // boundary. Retain mutability in the model for future ownership and
            // direction diagnostics.
            let _ = mutable;
            match inner.as_ref() {
                Type::Pointer { .. } => Some(format!(
                    "Ref[{}]",
                    raw_pointer_carrier_name(inner, type_rename)?
                )),
                Type::Path(p)
                    if use_bytes
                        && matches!(
                            p.rsplit("::").next(),
                            Some("c_char" | "i8" | "u8" | "c_schar" | "c_uchar")
                        ) =>
                {
                    Some("Bytes".into())
                }
                Type::Path(p)
                    if matches!(
                        p.rsplit("::").next(),
                        Some("c_char" | "i8" | "u8" | "c_schar" | "c_uchar")
                    ) =>
                {
                    raw_pointer_carrier_name(ty, type_rename)
                }
                Type::Path(p) if p.ends_with("c_void") => Some("RawPtr".into()),
                Type::Path(p) if primitive_moon_type(p).is_some() => {
                    Some(format!("Ref[{}]", primitive_moon_type(p)?))
                }
                Type::Path(p) => Some(renamed_type_ident(p.rsplit("::").next()?, type_rename)),
                _ => moon_type_config(inner, type_rename, use_bytes).map(|ty| format!("Ref[{ty}]")),
            }
        }
        Type::Array { inner, .. } => {
            moon_type_config(inner, type_rename, use_bytes).map(|t| format!("FixedArray[{t}]"))
        }
        Type::FunctionPointer {
            params,
            result,
            variadic,
            nullable,
        } => {
            if *variadic {
                return None;
            }
            let params = params
                .iter()
                .map(|ty| moon_type_config(ty, type_rename, use_bytes))
                .collect::<Option<Vec<_>>>()?
                .join(", ");
            let ty = format!(
                "FuncRef[({params}) -> {}]",
                moon_type_config(result, type_rename, use_bytes)?
            );
            Some(if *nullable { format!("{ty}?") } else { ty })
        }
        Type::Unsupported => None,
    }
}
fn needs_ownership(t: &Type) -> bool {
    matches!(
        t,
        Type::Pointer { .. } | Type::Array { .. } | Type::FunctionPointer { .. }
    )
}

fn needs_ownership_resolved(t: &Type, model: &Model) -> bool {
    match t {
        Type::Path(path) => model
            .aliases
            .get(path.rsplit("::").next().unwrap_or(path))
            .is_some_and(|alias| needs_ownership_resolved(alias, model)),
        _ => needs_ownership(t),
    }
}

fn is_direct_ffi_type(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Unit => true,
        Type::Path(path) => {
            let name = path.rsplit("::").next().unwrap_or(path);
            if primitive_moon_type(path).is_some() || name == "c_void" {
                return true;
            }
            if model.structs.contains_key(name) {
                return false;
            }
            model
                .aliases
                .get(name)
                .is_some_and(|alias| is_direct_ffi_type(alias, model))
        }
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::Array { .. } => false,
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unsupported => false,
    }
}

fn is_pointer_pointee(ty: &Type, model: &Model) -> bool {
    match ty {
        Type::Path(_) => true,
        Type::Pointer { inner, .. } => is_pointer_pointee(inner, model),
        Type::FunctionPointer {
            params,
            result,
            variadic,
            ..
        } => {
            !variadic
                && params.iter().all(|param| is_direct_ffi_type(param, model))
                && is_direct_ffi_type(result, model)
        }
        Type::Unit | Type::Array { .. } | Type::Unsupported => false,
    }
}
fn moon_parameter_type(
    ty: &Type,
    model: &Model,
    function: &str,
    parameter: &str,
    resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    type_rename: fn(String) -> String,
    use_bytes: bool,
) -> Option<String> {
    let rendered = moon_type_config(ty, type_rename, use_bytes)?;
    if effective_nullability(
        resolver,
        function,
        NullabilityPosition::Parameter(parameter.to_owned()),
    ) == Nullability::Nullable
        && use_bytes
        && is_bytes_pointer(ty, model)
    {
        Some(format!("{rendered}?"))
    } else {
        Some(rendered)
    }
}

fn moon_result_type(
    ty: &Type,
    model: &Model,
    function: &str,
    resolver: &dyn Fn(&str, NullabilityPosition) -> Nullability,
    type_rename: fn(String) -> String,
    use_bytes: bool,
) -> Option<String> {
    let rendered = if pointer_depth(ty) >= 2 {
        raw_pointer_carrier_name(ty, type_rename)?
    } else {
        moon_type_config(ty, type_rename, use_bytes)?
    };
    if effective_nullability(resolver, function, NullabilityPosition::Return)
        == Nullability::Nullable
        && use_bytes
        && is_bytes_pointer(ty, model)
    {
        Some(format!("{rendered}?"))
    } else {
        Some(rendered)
    }
}

fn is_direct_byte_pointer(ty: &Type) -> bool {
    matches!(ty, Type::Pointer { inner, .. } if matches!(inner.as_ref(), Type::Path(path) if matches!(path.rsplit("::").next(), Some("u8" | "i8" | "c_char" | "c_schar" | "c_uchar"))))
}

fn is_bytes_pointer(ty: &Type, model: &Model) -> bool {
    let Type::Pointer { inner, .. } = ty else {
        return false;
    };
    let mut inner = inner.as_ref();
    let mut seen = BTreeSet::new();
    loop {
        let Type::Path(path) = inner else {
            return false;
        };
        let name = path.rsplit("::").next().unwrap_or(path);
        if matches!(name, "c_char" | "i8" | "u8") {
            return true;
        }
        if !seen.insert(name) {
            return false;
        }
        let Some(alias) = model.aliases.get(name) else {
            return false;
        };
        inner = alias;
    }
}
fn collect_opaque(t: &Type, model: &Model, out: &mut BTreeSet<String>) {
    match t {
        Type::Pointer { inner, .. } => {
            if let Type::Path(p) = inner.as_ref() {
                let n = p.rsplit("::").next().unwrap();
                if n == "c_void" {
                    out.insert("RawPtr".into());
                } else if !is_primitive(n)
                    && !model.structs.contains_key(n)
                    && !model.aliases.contains_key(n)
                {
                    out.insert(n.into());
                }
            } else {
                collect_opaque(inner, model, out);
            }
        }
        Type::Array { inner, .. } => collect_opaque(inner, model, out),
        Type::FunctionPointer { params, result, .. } => {
            for param in params {
                collect_opaque(param, model, out);
            }
            collect_opaque(result, model, out);
        }
        _ => {}
    }
}
fn contains_pointer_to_value_struct(t: &Type, value_structs: &BTreeSet<String>) -> bool {
    match t {
        Type::Pointer { inner, .. } => match inner.as_ref() {
            Type::Path(path) => value_structs.contains(path.rsplit("::").next().unwrap_or(path)),
            other => contains_pointer_to_value_struct(other, value_structs),
        },
        Type::Array { inner, .. } => contains_pointer_to_value_struct(inner, value_structs),
        Type::FunctionPointer { params, result, .. } => {
            params
                .iter()
                .any(|param| contains_pointer_to_value_struct(param, value_structs))
                || contains_pointer_to_value_struct(result, value_structs)
        }
        _ => false,
    }
}
fn is_primitive(s: &str) -> bool {
    matches!(
        s,
        "i8" | "u8"
            | "i16"
            | "u16"
            | "i32"
            | "u32"
            | "i64"
            | "u64"
            | "isize"
            | "usize"
            | "f32"
            | "f64"
            | "bool"
            | "c_char"
            | "c_schar"
            | "c_uchar"
            | "c_short"
            | "c_ushort"
            | "c_int"
            | "c_uint"
            | "c_long"
            | "c_ulong"
            | "c_longlong"
            | "c_ulonglong"
            | "c_float"
            | "c_double"
            | "c_void"
    )
}

fn primitive_moon_type(path: &str) -> Option<&'static str> {
    match path.rsplit("::").next()? {
        "i8" | "u8" | "c_char" | "c_schar" | "c_uchar" => Some("Byte"),
        "i16" | "u16" | "c_short" | "c_ushort" | "i32" | "c_int" => Some("Int"),
        "u32" | "c_uint" => Some("UInt"),
        "i64" | "c_longlong" | "isize" | "c_long" => Some("Int64"),
        "u64" | "c_ulonglong" | "usize" | "c_ulong" | "size_t" => Some("UInt64"),
        "f32" | "c_float" => Some("Float"),
        "f64" | "c_double" => Some("Double"),
        "bool" => Some("Bool"),
        _ => None,
    }
}
fn warning(item: &str, message: &str) -> Diagnostic {
    Diagnostic {
        level: DiagnosticLevel::Warning,
        item: item.into(),
        message: message.into(),
    }
}
fn safe_ident(s: &str) -> String {
    let s = s.replace("r#", "");
    if matches!(
        s.as_str(),
        "type"
            | "fn"
            | "let"
            | "const"
            | "struct"
            | "enum"
            | "match"
            | "if"
            | "else"
            | "loop"
            | "for"
            | "while"
            | "return"
            | "extern"
            | "pub"
            | "priv"
            | "true"
            | "false"
    ) {
        format!("{s}_")
    } else {
        s
    }
}

fn safe_value_ident(s: &str) -> String {
    let raw = s.replace("r#", "").to_snake_case();
    if raw.is_empty() {
        return "value".into();
    }
    safe_ident(&raw)
}

fn renamed_value_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_type_ident(s: &str, rename: fn(String) -> String) -> String {
    safe_ident(&rename(s.to_owned()))
}

fn renamed_constant_ident(s: &str, rename: fn(String) -> String) -> String {
    let name = rename(s.to_owned());
    if name.is_empty() {
        "CONSTANT".into()
    } else {
        safe_ident(&name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{model::Model, parse};
    use heck::{ToShoutySnakeCase, ToUpperCamelCase};
    fn default_function_rename(name: String) -> String {
        name.to_snake_case()
    }
    fn default_type_rename(name: String) -> String {
        name.to_upper_camel_case()
    }
    fn default_constant_rename(name: String) -> String {
        name.to_shouty_snake_case()
    }
    fn default_nullability(_: &str, _: NullabilityPosition) -> Nullability {
        Nullability::Unspecified
    }
    #[test]
    fn generates_ffi() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Point { pub x:i32,pub y:i32 }
pub const ANSWER:u32=42;
unsafe extern "C" { pub fn c_move(p:*mut Point,n:usize)->i32; }
#[unsafe(no_mangle)] pub extern "C" fn rust_ping(value:u64)->bool { true }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "// custom footer",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("#external\ntype Point"));
        assert!(
            b.moonbit_source()
                .contains("fn Point::new(x : Int, y : Int) -> Point")
        );
        assert!(
            b.c_stub_source()
                .contains("void *moon_bindgen_point_new(int32_t x, int32_t y)")
        );
        assert!(
            b.moonbit_source()
                .contains("fn Point::get_x(self : Point) -> Int")
        );
        assert!(
            b.moonbit_source()
                .contains("fn Point::set_y(self : Point, value : Int) -> Unit")
        );
        assert!(
            b.c_stub_source()
                .contains("int32_t moon_bindgen_point_x_get(void *self)")
        );
        assert!(b.moonbit_source().contains("#borrow(p)"));
        assert!(
            b.moonbit_source()
                .contains("fn c_move(p : Point, n : UInt64) -> Int")
        );
        assert!(
            b.moonbit_source()
                .contains("fn rust_ping(value : UInt64) -> Bool")
        );
        assert!(b.moonbit_source().ends_with("// custom footer\n"));
    }

    #[test]
    fn generates_function_pointer_aliases_and_direct_callbacks() {
        let f = syn::parse_file(
            r#"
pub type Compare = ::std::option::Option<unsafe extern "C" fn(a: i32, b: i32) -> i32>;
unsafe extern "C" {
  pub fn sort_items(compare: Compare);
  pub fn get_callback() -> unsafe extern "C" fn(value: u64);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(
            b.moonbit_source()
                .contains("type Compare = FuncRef[(Int, Int) -> Int]?")
        );
        assert!(b.moonbit_source().contains("#borrow(compare)"));
        assert!(
            b.moonbit_source()
                .contains("fn sort_items(compare : Compare)")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_callback() -> FuncRef[(UInt64) -> Unit]")
        );
        assert!(b.diagnostics().is_empty());
    }

    #[test]
    fn emits_nullable_bytes_parameters_directly() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn connect(server_name: *const ::std::os::raw::c_char, id: *const u8);
                pub fn optional_data() -> *const u8;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &|function, position| match (function, position) {
                ("connect", NullabilityPosition::Parameter(name)) if name == "server_name" => {
                    Nullability::Nullable
                }
                _ => Nullability::Unspecified,
            },
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(
            b.moonbit_source()
                .contains("fn connect(server_name : Bytes?, id : Bytes)")
        );
        assert!(b.moonbit_source().contains("#borrow(server_name, id)"));
        assert!(b.moonbit_source().contains("fn optional_data() -> Bytes?"));
    }

    #[test]
    fn forward_declares_structs_referenced_by_pointer_fields() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Node { pub next: *const Node, pub value: i32 }
unsafe extern "C" { pub fn visit(node: *const Node); }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        let c = b.c_stub_source();
        let declaration = "typedef struct moon_bindgen_c_Node moon_bindgen_c_Node;";
        let definition = "struct moon_bindgen_c_Node {";
        assert!(c.find(declaration).unwrap() < c.find(definition).unwrap());
        assert!(c.contains("return (void *)value->next;"));
    }

    #[test]
    fn normalizes_c_function_names_and_groups_borrows() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_copy(src: *const i8, dst: *mut i8) -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("#borrow(src, dst)"));
        assert!(b.moonbit_source().contains("fn lz4_copy("));
        assert!(b.moonbit_source().contains("= \"LZ4_copy\""));
    }

    #[test]
    fn emits_public_types_and_functions_when_configured() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Context { _private: [u8; 0] }
pub type Count = u32;
pub const DEFAULT_COUNT: Count = 3;
unsafe extern "C" { pub fn library_count(context: *mut Context) -> Count; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("#external\npub type Context"));
        assert!(b.moonbit_source().contains("pub type Count = UInt"));
        assert!(
            b.moonbit_source()
                .contains("pub const DEFAULT_COUNT : Count = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("pub extern \"c\" fn library_count")
        );
    }

    #[test]
    fn filters_methods_using_original_rust_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn LZ4_keep() -> i32;
                pub fn XXH_drop() -> i32;
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |name| name.starts_with("LZ4_"),
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("fn lz4_keep"));
        assert!(!b.moonbit_source().contains("xxh_drop"));
        assert!(!b.moonbit_source().contains("XXH_drop"));
    }

    #[test]
    fn filters_types_and_constants_by_original_rust_names() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct KeepType { value: i32 }
#[repr(C)] pub struct DropType { value: i32 }
pub type KeepAlias = u32;
pub type DropAlias = u32;
pub const KEEP_CONST: u32 = 1;
pub const DROP_CONST: u32 = 2;
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |name| name.starts_with("Keep"),
            |name| name.starts_with("KEEP"),
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("type KeepType"));
        assert!(b.moonbit_source().contains("type KeepAlias"));
        assert!(!b.moonbit_source().contains("DropType"));
        assert!(!b.moonbit_source().contains("DropAlias"));
        assert!(b.moonbit_source().contains("const KEEP_CONST"));
        assert!(!b.moonbit_source().contains("DROP_CONST"));
    }

    #[test]
    fn normalizes_lowercase_types_and_scalar_pointers() {
        let f = syn::parse_file(
            r#"
pub type int_fast16_t = i16;
pub type stream_t = stream_u;
#[repr(C)] pub union stream_u { value: i32 }
unsafe extern "C" {
  pub fn update(value: *mut ::std::os::raw::c_int, stream: *mut stream_t);
  pub fn get_context(value: *mut *mut Context);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("type IntFast16T = Int"));
        assert!(b.moonbit_source().contains("type StreamT = StreamU"));
        assert_eq!(b.moonbit_source().matches("type StreamT").count(), 1);
        assert!(
            b.moonbit_source()
                .contains("fn update(value : Ref[Int], stream : StreamT)")
        );
        assert!(!b.moonbit_source().contains("type c_int"));
        assert!(
            b.moonbit_source()
                .contains("fn get_context(value : Ref[Ptr[Context]])")
        );
        assert!(
            b.c_stub_source()
                .starts_with("// Generated by moon-bindgen. Do not edit.\n#include <moonbit.h>")
        );
        assert!(b.c_stub_source().contains("moon_bindgen_ptr_ptr_context"));
    }

    #[test]
    fn resolves_aliases_that_collapse_to_the_same_moonbit_name() {
        let f = syn::parse_file(
            r#"
pub type __int16_t = ::std::os::raw::c_short;
pub type __int8_t = i8;
pub type __int32_t = i32;
pub type __int64_t = i64;
pub type int_least8_t = __int8_t;
pub type int_least16_t = __int16_t;
pub type int_least32_t = __int32_t;
pub type int_least64_t = __int64_t;
pub type __uint8_t = u8;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __uint32_t = u32;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type uint_least8_t = __uint8_t;
pub type uint_least16_t = __uint16_t;
pub type uint_least32_t = __uint32_t;
pub type uint_least64_t = __uint64_t;
pub type uintmax_t = __uint64_t;
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |name| !name.starts_with('_'),
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("pub type IntLeast16T = Int"));
        assert!(b.moonbit_source().contains("pub type IntLeast8T = Byte"));
        assert!(b.moonbit_source().contains("pub type IntLeast32T = Int"));
        assert!(b.moonbit_source().contains("pub type IntLeast64T = Int64"));
        assert!(b.moonbit_source().contains("pub type UintLeast8T = Byte"));
        assert!(b.moonbit_source().contains("pub type UintLeast16T = Int"));
        assert!(b.moonbit_source().contains("pub type UintLeast32T = UInt"));
        assert!(
            b.moonbit_source()
                .contains("pub type UintLeast64T = UInt64")
        );
        assert!(b.moonbit_source().contains("pub type UintmaxT = UInt64"));
        assert!(!b.moonbit_source().contains("IntLeast16T = IntLeast16T"));
        assert!(!b.moonbit_source().contains("UintmaxT = UintmaxT"));
    }

    #[test]
    fn resolves_parameter_ownership_with_original_names() {
        let f = syn::parse_file(
            r#"unsafe extern "C" {
                pub fn register_data(kept: *mut u8, temporary: *const u8, raw: *mut u8);
            }"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|function, parameter| match (function, parameter) {
                ("register_data", "kept") => Ownership::Owned,
                _ => Ownership::Borrow,
            },
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("#owned(kept)"));
        assert!(b.moonbit_source().contains("#borrow(temporary, raw)"));
        assert!(!b.moonbit_source().contains("#owned(raw)"));
    }

    #[test]
    fn generates_struct_value_stubs_and_skips_remaining_unsupported_signatures() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Value { field: i32 }
unsafe extern "C" {
  pub fn by_value(value: Value) -> Value;
  pub fn double_pointer(value: *mut *mut i32);
  pub fn context_pointer(value: *mut *mut Context);
  pub fn triple_pointer(value: *mut *mut *mut Context);
  pub fn raw_double_pointer(value: *mut *mut ::std::ffi::c_void);
  pub fn byte_double_pointer(value: *mut *mut u8);
  pub fn nullable(value: Option<*mut Value>);
  pub fn supported(value: *mut Value);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("struct Value"));
        assert!(b.moonbit_source().contains("fn by_value"));
        assert!(b.c_stub_source().contains("moon_bindgen_by_value"));
        assert!(b.c_stub_source().contains("moonbit_make_bytes"));
        assert!(
            b.moonbit_source()
                .contains("fn double_pointer(value : Ref[Ptr[Int]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn context_pointer(value : Ref[Ptr[Context]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn triple_pointer(value : Ref[Ptr[Ptr[Context]]])")
        );
        assert!(b.moonbit_source().contains("#external\ntype Ptr[T]"));
        assert!(
            b.moonbit_source()
                .contains("fn moon_bindgen_ptr_context_null() -> Ptr[Context]")
        );
        assert!(
            b.moonbit_source()
                .contains("fn moon_bindgen_ptr_ptr_context_null() -> Ptr[Ptr[Context]]")
        );
        assert!(b.c_stub_source().contains("moon_bindgen_ptr_ptr_context"));
        assert!(
            b.moonbit_source()
                .contains("fn raw_double_pointer(value : Ref[Ptr[Unit]])")
        );
        assert!(
            b.moonbit_source()
                .contains("fn byte_double_pointer(value : Ref[Ptr[Byte]])")
        );
        assert!(b.moonbit_source().contains("#external\ntype Ptr[T]"));
        assert!(!b.moonbit_source().contains("fn nullable"));
        assert!(!b.moonbit_source().contains("fn supported"));
        assert_eq!(b.diagnostics().len(), 2);
    }

    #[test]
    fn generates_nested_struct_dependencies_and_fixed_array_marshalling() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Inner { value: i32, bytes: [u8; 4] }
#[repr(C)] pub struct Outer { inner: Inner, enabled: bool }
#[repr(C)] pub struct PointerHolder { value: *mut *mut i32 }
unsafe extern "C" {
  pub fn round_trip(value: Outer) -> Outer;
  pub fn consume_pointer_holder(value: PointerHolder);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("pub(all) struct Inner"));
        assert!(b.moonbit_source().contains("value : Ref[Ref[Int]]"));
        assert!(b.c_stub_source().contains("int32_t * * value_value"));
        assert!(b.moonbit_source().contains("pub(all) struct Outer"));
        assert!(
            b.moonbit_source()
                .contains("value.inner.bytes.length() != 4")
        );
        assert!(
            b.c_stub_source()
                .contains("memcpy(moon_bindgen_arg_value.inner.bytes")
        );
        assert!(
            b.c_stub_source()
                .contains("moonbit_make_bytes((int32_t)sizeof(result), 0)")
        );
    }

    #[test]
    fn defaults_external_pointer_returns_to_nullable_and_allows_overrides() {
        let f = syn::parse_file(
            r#"
#[repr(C)] pub struct Context { _private: [u8; 0] }
unsafe extern "C" {
  pub fn get_default() -> *mut Context;
  pub fn get_nonnull() -> *mut Context;
  pub fn set_default(value: *mut Context);
  pub fn set_nullable(value: *mut Context);
}
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let b = render(
            &m,
            "",
            "",
            Visibility::Public,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &|function, position| match (function, position) {
                ("get_nonnull", NullabilityPosition::Return) => Nullability::NonNull,
                ("set_nullable", NullabilityPosition::Parameter(name)) if name == "value" => {
                    Nullability::Nullable
                }
                _ => Nullability::Unspecified,
            },
            default_function_rename,
            default_type_rename,
            default_constant_rename,
            true,
            true,
        );
        let moon = b.moonbit_source();
        assert!(moon.contains("pub fn get_default() -> Context?"));
        assert!(moon.contains("pub extern \"c\" fn get_nonnull() -> Context"));
        assert!(moon.contains("pub extern \"c\" fn set_default(value : Context)"));
        assert!(moon.contains("pub fn set_nullable(value : Context?)"));
        assert!(moon.contains("None => Context::null()"));
        assert!(moon.contains("if result.is_null()"));
    }

    #[test]
    fn renames_functions_types_constants_and_type_references() {
        let f = syn::parse_file(
            r#"
pub type LIB_count_t = u32;
pub const LIB_DEFAULT_COUNT: LIB_count_t = 3;
unsafe extern "C" { pub fn LIB_getCount() -> LIB_count_t; }
"#,
        )
        .unwrap();
        let mut m = Model::default();
        parse::collect_file(&f, &mut m);
        let function_rename =
            |name: String| name.strip_prefix("LIB_").unwrap_or(&name).to_snake_case();
        let type_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_upper_camel_case()
        };
        let constant_rename = |name: String| {
            name.strip_prefix("LIB_")
                .unwrap_or(&name)
                .to_shouty_snake_case()
        };
        let b = render(
            &m,
            "",
            "",
            Visibility::Private,
            |_| true,
            |_| true,
            |_| true,
            &|_, _| Ownership::Borrow,
            &default_nullability,
            function_rename,
            type_rename,
            constant_rename,
            true,
            true,
        );
        assert!(b.moonbit_source().contains("type CountT = UInt"));
        assert!(
            b.moonbit_source()
                .contains("const DEFAULT_COUNT : CountT = 3")
        );
        assert!(
            b.moonbit_source()
                .contains("fn get_count() -> CountT = \"LIB_getCount\"")
        );
    }
}
